### ISSUE TITLE
Decide how to expose Cassandra configuration

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#10]
cass-operator has the `Config` property which is basically an opaque, JSON blob. You can specify anything that [config-builder](https://github.com/datastax/cass-config-builder) supports. In k8ssandra 1.x we are only exposing particular Cassandra/JVM settings in a much more fined-grained fashion. The purpose of this ticket is to determine what we want to do in k8ssandra-operator.

Exposing the `Config` property provides flexibility. Following the approach we have taken in k8ssandra 1.x provides more control. Let me provide an example that I like to use where that control can be useful. Suppose a C* node is down longer than the max hint window. When it comes back up, k8ssandra-operator can schedule a repair to make sure it receives any writes it missed.

I see the benefits of having more control, but I also see the benefits of providing flexibility. I think it would be worthwhile to consider a way to allow users to provide their own config files that would override defaults.

It might be worthwhile to solicit feedback on this from external users/contributors. I am happy to provide as much detail as necessary on how the current config provisioning works :)

bradfordcp jeffreyscarpenter  thoughts?

┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-585) by [Unito](https://www.unito.io)
┆Epic: Exposing Cassandra Configuration
┆Issue Number: K8SSAND-585
┆Priority: Medium

**Comment by jeffreyscarpenter** [comment]
I'd come down on the side of flexibility for a couple of reasons.

- If a user is asking for an additional setting to be exposed, we should assume they have a good reason for doing so, and providing a generic mechanism gives them the flexibility to make the configuration change they need without having to wait on an issue or submit a PR. We can still curate a list of the most important configuration options and expose them via K8ssandra.
- In general, we should probably expect that any cass-operator feature not exposed via K8ssandra will be requested. Having a posture where we default to making cass-operator features accessible in K8ssandra will prevent a lot of confusion and incoming issues / feature requests.

**Comment by jsanda** [comment]
While doing some testing for multi-cluster, I realized that the K8ssandraCluster controller will need to configure some settings, namely the replication for system keyspaces like `system_auth`. This means that we will need to merge user-supplied values with those that the K8ssandraCluster controller sets.

As it turns out cass-operator already does this. It has some properties, mostly for DSE, that it adds to the config. The value of `config` is parsed into JSON and is then passed via an environment variable to the `cassandra` container.  The environment variable is created in the [getConfigDataEnVars](https://github.com/k8ssandra/cass-operator/blob/master/pkg/reconciliation/construct_podtemplatespec.go#L333) function.

`getConfigDataEnVars` calls `GetConfigAsJson` (see [here](https://github.com/k8ssandra/cass-operator/blob/c757597b1eb2f8845ccdc5685b342c153f03f5ef/api/v1beta1/cassandradatacenter_types.go#L562)). This function combines user-supplied values with those that cass-operator adds. See [here](https://github.com/k8ssandra/cass-operator/blob/c757597b1eb2f8845ccdc5685b342c153f03f5ef/api/v1beta1/cassandradatacenter_types.go#L620).

We can call `GetConfigAsJson` from the K8ssandraCluster controller, but it would be nice if we can refactor it so that we can reuse the merging code.

@burmanm wdyt?

**Comment by jsanda** [comment]
Thinking out loud...

Let me provide some more details and context to my previous comments. My [multi-cluster branch](https://github.com/jsanda/k8ssandra-operator/tree/multi-cluster) is the current development branch. The K8sandraCluster type does not directly embed CassandraDatacenterSpec. Instead I have defined CassandraDatacenterTemplateSpec (see [here](https://github.com/jsanda/k8ssandra-operator/blob/multi-cluster/api/v1alpha1/k8ssandracluster_types.go#L71)). It defines a subset of the fields in CassandraDatacenterSpec. It also adds some additional fields. A CassandraDatacenter is created based off of the CassandraDatacenterTemplateSpec.

It would be nice if we could reuse the `GetConfigAsJson` function with CassandraDatacenterTemplateSpec. Furthermore, it would be nice if I could pass the function a set of additional properties to be merged with the user-supplied ones.
