### ISSUE TITLE
Add support for nodeSelector and tolerations to operator resources

### ISSUE THREAD

**Issue by vsoloviov** [k8ssandra/k8ssandra-operator#1010]
**What is missing?**
Deployment installed by k8ssandra-operator is missing nodeSelector and toleration parameters.

**Why do we need it?**
In some environments with strict network rules operator must be installed on the same nodes group as Cassandra to be able to communicate with cluster. Tolerations and nodeSelector may help placing operator resources in a proper nodes set.

**Environment**

* K8ssandra Operator version:
Any

**Anything else we need to know?**:
I'm going to open a PR here soon, also similar issue/PR to be created for cass-operator

**Comment by Miles-Garnsey** [comment]
Hi @vsoloviov, we welcome PRs, how is this coming along? 

We do allow setting tolerations on Cassandra pods, which particular components are you wanting to specify more detailed placement for? 

As an FYI, our preference is to avoid nodeSelector in favour of affinities and tolerations, because they are generally more flexible.  Is there a reason you prefer nodeSelector in this case?

**Comment by vsoloviov** [comment]
Hi @Miles-Garnsey, thank you for a feedback.

> We do allow setting tolerations on Cassandra pods, which particular components are you wanting to specify more detailed placement for?

That's correct, tolerations can be set for Cassandra pods, however, not for operator pods.

I opened a PR a while ago https://github.com/k8ssandra/k8ssandra-operator/pull/1011

I don't mind changing `nodeSelector` to affinities, however, I already added `nodeSelector` to cass-operator: https://github.com/k8ssandra/k8ssandra/pull/1613
So for consistency I think it makes sense to have `nodeSelector` here as well.
What do you think?

**Comment by vsoloviov** [comment]
@Miles-Garnsey @adejanovski could you please take a look? This is a tiny change

**Comment by adejanovski** [comment]
Hi @vsoloviov, I've added this issue to our "Ready for review" list. We'll process it as soon as possible.
Thanks for your patience, and for the contribution of course!
