### ISSUE TITLE
priorityClassName support

### ISSUE THREAD

**Issue by Mokto** [k8ssandra/k8ssandra-operator#1034]
### What is missing?
priorityClassName support is surprisingly missing from the CRD.

Maybe I'm missing something but it doesn't seem possible right now to set this value.

### Why is this needed?
It's a standard (and highly used) field in Kubernetes.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-85) by [Unito](https://www.unito.io)
┆Fix Versions: 2024-10,2024-11,2025-01
┆Issue Number: K8OP-85

**Comment by JBOClara** [comment]
I was thinking that this project is using K8ssandraCluster because of this
https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/k8ssandra/v1alpha1/k8ssandracluster_types.go

**Comment by cnosari** [comment]
Hi, i have the same problem. Would it be possible to include in the CDRs the possibility of setting the priorityClass for the K8ssandraCluster Kind? Because it would be useful during a possible fault, resulting in a restart or shutdown, of the workers's cluster
thanks
