### ISSUE TITLE
Check if data_endpoint_auth keyspace exists

### ISSUE THREAD

**Issue by adutra** [k8ssandra/k8ssandra-operator#106]
**What is missing?**

See https://github.com/k8ssandra/k8ssandra-operator/pull/100#discussion_r700316041 for context.

The controller currently calls the `CreateKeyspace` endpoint for every Stargate resource tha it creates, in order to ensure that the `data_endpoint_auth` exists.
As a long-term solution, we are going to create a new Management API endpoint to list existing keyspaces.
Once this new endpoint is available, this PR would then change the controller code to call that endpoint first, and only call the `CreateKeyspace` endpoint if the `data_endpoint_auth` keyspace is not present yet.

**Why do we need it?**

In order to avoid issuing `CREATE KEYSPACE` statements for nothing.

**Environment**

Irrelevant

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-855) by [Unito](https://www.unito.io)
┆Reviewer: 557058:376e6d8d-84b1-46a1-a227-0887055aa65a
┆Epic: Stargate Controller Integration
┆Fix Versions: k8ssandra-operator-1.0.0-alpha.1
┆Issue Number: K8SSAND-855
┆Priority: Medium

**Comment by adutra** [comment]
Relevant Management API issue: https://github.com/k8ssandra/management-api-for-apache-cassandra/issues/126.

**Comment by jsanda** [comment]
As I noted in https://github.com/k8ssandra/k8ssandra-operator/pull/100#discussion_r700693849 we should only be make the call to create the auth keyspace once prior to reconciling any Stargate instances.
