### ISSUE TITLE
Document high-level capability overview

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#107]
**What is missing?**
A high-level overview of the general capabilities, current limitations, and future capability plans for the operator.

**Why do we need it?**
So that new-comers to the project can get an idea of what they should expect from the current state of the operator.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-857) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-2.0.0-alpha
┆Issue Number: K8SSAND-857
┆Priority: Medium

**Comment by johnsmartco** [comment]
Covered in:

- https://docs-v2.k8ssandra.io/components/k8ssandra-operator/
- https://docs-v2.k8ssandra.io/components/k8ssandra-operator/architecture/

If more "high-level capability..." info is needed, reopen this Issue.
