### ISSUE TITLE
Refresh the users secrets after a remote restore to recreate them in the database

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1080]
After performing a remote restore, the token allocations will have changed but the system_auth keyspace will remain untouched, making entries from the roles table potentially inaccessible.
We need to perform a bogus update on the various secrets that contain user credentials (see [here](https://docs.k8ssandra.io/tasks/secure/security/#secrets) for a full list) by adding a `k8ssandra.io/refresh` annotation with a timestamp.
This will trigger a reconcile in cass-operator that will recreate the different roles and allow logging into the cluster.

```[tasklist]
### Definition of Done
- [ ] After a remote restore was performed, users secrets are updated with an annotation to recreate the users in Cassandra
```

**Comment by Miles-Garnsey** [comment]
> This will trigger a reconcile in cass-operator that will recreate the different roles and allow logging into the cluster.

Is this functionality that already exists? I can pick this ticket up if it is still relevant.

**Comment by adejanovski** [comment]
Yes, turns out cass-operator picks up on superuser secrets refresh and updates them in the database.
Ticket is totally relevant, happy for you to pick it up.

**Comment by Miles-Garnsey** [comment]
There's a problem here. I've just been trying to implement this but the current way the `MedusaRestoreJobReconciler` is defined, it isn't aware of the presence of K8ssandraClusters.

It knows about cassandraDatacenters, but all of the fields relating to secrets are on the K8ssandraCluster object, not the cassDC object. What this means is that it is impossible to figure out what the secret names should be if they have been overridden in the K8ssandraCluster spec, since the backup/restore jobs may reside in a remote data plane where they don't have access to the K8ssandraCluster at all. 

I'll try to look at the secrets fields on the CassDC and match them back to the secrets listed in the docs, but there's no guarantee that these secrets are mounted through the CassDC fields and not through (e.g.) podTemplateSpec modifications on the cassDC manifest.

**Comment by Miles-Garnsey** [comment]
This is a bit different to what I would have expected. By default it looks like maybe everything is run from a superuserSecretRef. But there's also injection of a secret using the webhook (which is going to be hard to manage).

If we just wanted to create the secrets associated with the users array maybe that would be sufficient? Surely we don't need the Reaper UI secret at all..?


k8ssandraCluster | CassDC
-- | --
spec.cassandra.superuserSecretRef | spec.users[] (w. superuser: true)
spec.reaper.cassandraUserSecretRef | ??
spec.reaper.uiUserSecretRef | Do we need this?
spec.medusa.cassandraUserSecretRef | ??
?? | k8ssandra.io/inject-secret: '[{"name":"test-superuser","path":"/etc/secrets/test-superuser","containers":["cassandra"]}]'

**Comment by adejanovski** [comment]
> spec.reaper.uiUserSecretRef - Do we need this? It isn't related to a Cassandra user AFAIK.

Right, we can skip this one.
Your list looks about right: the superuser and both reaper/medusa users need the refresh.

> Moreover, if we want to refresh those secrets as part of a restore, I'm not sure it even makes sense to look at them from the perspective of the K8ssandraCluster, since the RestoreJobController operates at the DC level, not the cluster level.

mmmmh, seems like we have a loophole indeed. If the cassdc is not part of the k8ssandra-operator control plane, then we won't be able to update those secrets 🤔
I guess that v2 you're mentioning should include a k8s context in the Medusa(Backup|Restore)Job apis so that everything is handled in the control plane.

What are our options? k8ssandra-operator has watches on cassdc objects (even in remote DPs), so maybe the solution lies in adding an annotation on the cassdc that was restored to instruct the k8ssandra-operator CP to refresh the secrets?
Does it sound convoluted as a solution?

**Comment by Miles-Garnsey** [comment]
Apparently the tests are using the wrong image. When this is rebased against main after NY the failing test will start passing. I've also added version logging functionality at start up so that this can be detected in future.
