### ISSUE TITLE
Document high-level configuration overview

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#109]
**What is missing?**
An overview of the configuration options available when using the operator with examples of various Datacenter configurations.

**Why do we need it?**
So that a new-comer to project has an idea of what can be configured through the operator.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-859) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-2.0.0-alpha
┆Issue Number: K8SSAND-859
┆Priority: Medium

**Comment by johnsmartco** [comment]
Covered in https://docs-v2.k8ssandra.io/components/k8ssandra-operator/architecture/, but we have placeholders for related topics per component, e.g. in the section  https://docs-v2.k8ssandra.io/components/k8ssandra-operator/architecture/#cassandra-datacenters , "(Add link to configuration doc when it’s available.)"
