### ISSUE TITLE
Helm Chart v1.10.0 broken image reference

### ISSUE THREAD

**Issue by pschichtel** [k8ssandra/k8ssandra-operator#1109]
The image is constructed as `docker.io/cr.k8ssandra.io/k8ssandra/k8ssandra-operator:v1.10.0` instead of `cr.k8ssandra.io/k8ssandra/k8ssandra-operator:v1.10.0`, which is a misconfiguration in the values.yaml.

**Comment by adejanovski** [comment]
Thanks for the bug report. We'll fix this ASAP.

**Comment by pschichtel** [comment]
@adejanovski I created a PR already, see #1108
