### ISSUE TITLE
Installing helm chart for k8ssandra operator is giving below error

### ISSUE THREAD

**Issue by vinaykw** [k8ssandra/k8ssandra-operator#1116]
**After installing helm charts using the command helm install k8ssandra-operator k8ssandra-operator -n k8ssandra-operator --create-namespace**

Only cass operator pod is coming up and k8ssandra operator pod has failed with error 
```
2023-11-16T13:23:45.658Z        ERROR   setup   unable to create manager cluster connections    {"error": "no matches for kind \"ClientConfig\" in version \"config.k8ssandra.io/v1beta1\""}
main.main
        /workspace/main.go:163
runtime.main
        /usr/local/go/src/runtime/proc.go:250

```

**Did you expect to see something different?**

**How to reproduce it (as minimally and precisely as possible)**:
Just try installing helm chart for k8ssandra operator from https://github.com/k8ssandra/k8ssandra-operator/tree/main/charts/k8ssandra-operator

**Environment**

* K8ssandra Operator version:

    `https://github.com/k8ssandra/k8ssandra-operator/tree/main/charts/k8ssandra-operator
helm.sh/chart=k8ssandra-operator-1.11.0-SNAPSHOT`
    
    

* Kubernetes version information:

    `1.25`
    

* Kubernetes cluster kind:

    I created this cluster using VMs and installing k8s on them

* Manifests:

```
insert manifests relevant to the issue
```

* K8ssandra Operator Logs:

```
2023-11-16T13:23:42.503Z        INFO    setup   watch namespace configured      {"namespace": "k8ssandra-operator"}
2023-11-16T13:23:42.503Z        INFO    setup   watch namespace configured      {"namespace": "k8ssandra-operator"}
2023-11-16T13:23:43.055Z        INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8080"}
I1116 13:23:44.757063       1 request.go:690] Waited for 1.048483775s due to client-side throttling, not priority and fairness, request: GET:https://10.233.0.1:443/apis/discovery.k8s.io/v1?timeout=32s
2023-11-16T13:23:45.658Z        ERROR   setup   unable to create manager cluster connections    {"error": "no matches for kind \"ClientConfig\" in version \"config.k8ssandra.io/v1beta1\""}
main.main
        /workspace/main.go:163
runtime.main
        /usr/local/go/src/runtime/proc.go:250

```

**Anything else we need to know?**:

**Comment by adejanovski** [comment]
Hi @vinaykw,

I just installed it on a fresh cluster using `helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --create-namespace`, and it works fine.

The issue you're having is that you cannot install the helm chart from the GH repository itself because we generate the CRDs at release time in CI only. They're not stored in tree in the helm charts.

Try installing from [our helm repo](https://docs.k8ssandra.io/install/local/single-cluster-helm/#add-the-k8ssandra-helm-chart-repo) and you should be fine.

**Comment by vinaykw** [comment]
Hi,
Thanks for clarifying this point. I do not see in documentation anywhere that the chart need to be from the helm repo only and not from github? Is that a documentation problem?

Also, is it mandatory to have atleast 4 worker nodes in k8s cluster. One each for the datacenter pods and one for the startgate pod?. Is there a way circumvent the pod-antiaffinity checks for these pods?

**Comment by adejanovski** [comment]
You can use the [.spec.cassandra.softPodAntiAffinity](https://docs.k8ssandra.io/reference/crd/k8ssandra-operator-crds-latest/#k8ssandraclusterspeccassandra) setting to allow collocating Cassandra pods on the same workers.
That'll also require setting resource requests/limits for the Cassandra containers.

> I do not see in documentation anywhere that the chart need to be from the helm repo only and not from github? Is that a documentation problem?

Most likely yes.

**Comment by vinaykw** [comment]
Thanks Alex,
That means it is similar to the any normal yaml definition for k8s pod we can add additional elements to yaml file and apply it?
 
`One more question- Which is the latest version of the k8ssandra operator image, cass-operator image and corresponding cassandra DB version ? I have this version v1.18.2 for cass operator, v1.10.3 for k8ssandra operator and cassandra DB version is 4.0.4. Can we higher version for cassandra DB?`

**Comment by adejanovski** [comment]
> That means it is similar to the any normal yaml definition for k8s pod we can add additional elements to yaml file and apply it?

You should not modify the pods directly, just the K8ssandraCluster manifest.

> Which is the latest version of the k8ssandra operator image, cass-operator image and corresponding cassandra DB version ? I have this version v1.18.2 for cass operator, v1.10.3 for k8ssandra operator and cassandra DB version is 4.0.4. Can we higher version for cassandra DB?

These are the latest versions indeed for the operators. The latest 4.0 we support is [4.0.11](https://hub.docker.com/r/k8ssandra/cass-management-api/tags?page=1&name=4.0.11).

**Comment by adejanovski** [comment]
I'll go ahead and close this ticket now since we solved the initial issue.
