### ISSUE TITLE
Allow disabling Reaper UI auth

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1160]
Disabling Reaper's auth can theoretically be done by adding an empty name for `Reaper.spec.UiUserSecretRef`. In k8ssandra-operator though, we create a secret with credentials that's then added as a ref.
We need to introduce a way of disabling the auth for Reaper's UI to accommodate some use cases.

**Comment by Miles-Garnsey** [comment]
Quoted from another ticket:

> Is that correct? If we are creating a standalone Reaper instance here (via a Reaper CR, not the k8ssandraCluster CR) then can't we just set Reaper.spec.UiUserSecretRef == ""?

**Comment by adejanovski** [comment]
We could if we created a Reaper CR, but that doesn't work with k8ssandra-operator and we're relying on k8ssandra-operator.
