### ISSUE TITLE
jmx cleartext password has -rw-r--r-

### ISSUE THREAD

**Issue by lunarfs** [k8ssandra/k8ssandra-operator#118]
So according to the cassandra documentation it is recommended to do chmod 0400 on /etc/cassandra/jmxremote.password in order to secure the cleartext password as much as possible. k8ssandra currently exposes the password with -rw-r--r--

I think the file should have its permissions changed to 0400 after creation, and eventually the k8ssandra_superuser password should be rolled immediately after, or another password should be used for jmx.

So we stumbled over this because we were reading the k8ssandra-superuser Secret in order to use nodetool, but the password gets rolled  on a regular basis and we where unable to use nodetool until we started using the password stored in /etc/cassandra/jmxremote.password, so storing the JMX password this way is how Cassandra has implemented it, and there is not much to do about that if you want to use JMX during initialisation of the cluster. So this feature request is not about changing that, simply changing the permissions of the file to 0400 and eventually use another password than the superuser password as storing the superuser password in cleartext, even for a limited ammount of time seems wrong.

**Why do we need it?**
To secure the platform

**Environment**
kubernetes 1.19.x

* K8ssandra Operator version: 1.0

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-868) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-868
┆Priority: Medium

**Comment by jsanda** [comment]
Hi @lunarfs 

Can you recreate this issue in https://github.com/k8ssandra/k8ssandra?

**Comment by jdonenine** [comment]
Hey @lunarfs thanks for the report, is it safe to assume that you're using the full k8ssndra packaging (https://github.com/k8ssandra/k8ssandra) and not this operator?  The operator here (https://github.com/k8ssandra/k8ssandra-operator) is still under development and isn't quite ready for use yet.

If you're just checking it out and this is really the right place, that's awesome, but if not let's get this moved over to the other repo.

Thanks!

**Comment by lunarfs** [comment]
Hi, 
Thanks for letting me know, I will close this, and have already created an issue in https://github.com/k8ssandra/k8ssandra
BR
Frank
