### ISSUE TITLE
Expose the forceUpgradeRacks from the cassdc CRD

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1184]
We'd need to enable easy access to forcing racks to upgrade when they get stuck in a bad state and cannot recover.

The field should be exposed in the `CassandraDatacenterTemplate` type with the `forceUpgradeRacks` name.
Its value should be a list of string values, for each rack that is targeted.

```[tasklist]
### Definition of Done
- [ ] `forceUpgradeRacks` from the cassdc spec is exposed in the CassandraDatacenterTemplate and mapped appropriately during a reconcile.
```

**Comment by burmanm** [comment]
Related, which would make this feature obsolete in k8ssandra-operator: https://github.com/k8ssandra/cass-operator/issues/583
