### ISSUE TITLE
K8SSAND-878 ⁃ Should resources of system logger and config init containers be configurable?

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#120]
This is a follow up to https://github.com/k8ssandra/k8ssandra-operator/pull/94#discussion_r702723742 so it doesn't fall off the radar.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-878) by [Unito](https://www.unito.io)
┆Reviewer: 5fa4593062584c006b1e04d0
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-878
┆priority: Medium

**Comment by jdonenine** [comment]
@jsanda should we be thinking about revisiting this quickly before 1.0.0 so that we're not going out with an API that we're going to want to break later if we take the configurability away?

**Comment by jsanda** [comment]
Currently we are exposing a `systemLoggerResources` property for the server-system-logger container. I believe that property maps directly to one in the CassandraDatacenter spec.

We do not expose anything for the config init container. I think we should consistent and either have them both configurable or neither.

I am in favor of removing `systemLoggerResources` for now and coming back pos-1.0 to figure out how we want to expose them.

One thing that we may want to add now though is making the images configurable. Given the work we did in 1.x to support private registries, I would consider it a regression if we are deploying images whose coordinates are not configurable.

**Comment by jdonenine** [comment]
Cool, agreed on the short term there, let's use this ticket to remove systemLoggerResources.

I was under the impression that we already had support for private registries, I'd say that's a miss at the moment.  But, I wouldn't call it the end of the world either, probably something that will just have to wait for 1.1.

**Comment by jsanda** [comment]
I will create a PR to remove systemLoggerResources.

We do have support for private registries. We do not have support for configuring the image coordinates for the server-system-logger image or the config-builder image.

**Comment by jdonenine** [comment]
> We do have support for private registries. We do not have support for configuring the image coordinates for the server-system-logger image or the config-builder image.

Got it.  I'll clarify the new issue I created as such:  https://github.com/k8ssandra/k8ssandra-operator/issues/378
