### ISSUE TITLE
Restart the medusa container when the Medusa config changes

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1216]
Modifying the Medusa configuration (through a medusaConfiguration ref or not) will update the contents of the medusa.ini file through a configMap update.
The medusa container GRPC server won't restart though and won't take the new configuration into account.
We should make it so that the config file is monitored for changes and kill the process so that the container restarts with the new config.

We'd need to make sure no backup is in progress when we kill the medusa process.

```[tasklist]
### Definition of Done
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/1256
- [ ] https://github.com/k8ssandra/k8ssandra-operator/issues/1255
```

**Comment by rzvoncek** [comment]
I've created two tasks here, but in the end it seems they'll be handled by the same PR in Medusa anyway.

**Comment by rzvoncek** [comment]
@adejanovski this one looks like we can close it, right?

**Comment by adejanovski** [comment]
Yup, this is done

**Comment by Ranexia04** [comment]
Hi everyone,

I noticed that when i change configuration through K8ssandra Operator this will result in all pods being restarted at the same time leading to potential downtime in Production. Was this accounted for somehow? Did i miss something? Is there a way to turn off this feature (Like environment variable?)

Thanks in advance.
