### ISSUE TITLE
Update Controller-runtime to v0.17.2

### ISSUE THREAD

**Issue by Colvin-Y** [k8ssandra/k8ssandra-operator#1228]
**What is missing?**
We still run old controller-runtime 0.14.6. We should update to 0.17.2, go 1.21 and newer Kubernetes dependencies. This ticket only addresses the required changes to update, thus fixing removed fields.

**Why do we need it?**
Staying behind in versions of controller-runtime will cause issues later.

**Comment by adejanovski** [comment]
This was done as part of v1.17.0
