### ISSUE TITLE
K8SSAND-890 ⁃ #130 - Update e2e tests in GHA to against both Cassandra 3.11.x and 4.0.x

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#130]
In GHA we only run the e2e tests against Cassandra 3.11.x right. We should be running the tests against 4.0.x as well. If we already had that set up, we would have caught #129 earlier.

In the e2e tests we configure and deploy the K8ssandraCluster with kubectl. We already have support in place for passing arguments to the tests. In the Makefile we have:

```
PHONY: e2e-test
e2e-test:
ifdef E2E_TEST
	@echo Running e2e test $(E2E_TEST)
	go test -v -timeout 3600s ./test/e2e/... -run="$(E2E_TEST)" -args $(TEST_ARGS)
else
	@echo Running e2e tests
	go test -v -timeout 3600s $(TEST_ARGS) ./test/e2e/...
endif
```

Note the `-args` We can pass a `cassandraVersion` argument here.  Then we can create a separate K8ssandraCluster manifest for 4.0.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-890) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-890
┆priority: Medium

**Comment by jdonenine** [comment]
This issue was abandoned in favor of https://github.com/k8ssandra/k8ssandra-operator/issues/360
