### ISSUE TITLE
Add support for deploying the operator to data plane clusters

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#131]
The operator is configured by default to run in control plane mode. If you run `make deploy` it will install the operator but we currently lack support for configuring the operator and deploying it to a data plane cluster.

We need a couple of things to address this:

* A Kustomization directory that applies the necessary changes to the operator configuration
  * Note that this will be change once we do #63.
* An update in the Makefile
  * Maybe something like `make CONTROL_PLANE=false deploy`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-891) by [Unito](https://www.unito.io)
┆Fix Versions: k8ssandra-operator-1.0.0-beta.1
┆Issue Number: K8SSAND-891
┆Priority: Medium

**Comment by burmanm** [comment]
This support is added in the Helm charts in PR https://github.com/k8ssandra/k8ssandra/pull/1080

**Comment by jsanda** [comment]
closed by k8ssandra/k8ssandra#1080 and #144
