### ISSUE TITLE
Swapped interval and timeout

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#1316]
**What happened?**

In the e2e tests, there are instances where the timeout and interval are swapped within the arguments list. This causes no issues in the current setup, https://github.com/k8ssandra/k8ssandra-operator/pull/1314/commits/6a05eeac031d5e757d7e38637cc4775de38b9113.

**Comment by adejanovski** [comment]
I think this got merged with #1314

**Comment by adejanovski** [comment]
I think this got merged with #1314

**Comment by Miles-Garnsey** [comment]
> I think this got merged with https://github.com/k8ssandra/k8ssandra-operator/pull/1314

It did ;)
