### ISSUE TITLE
Vector container is not correctly created in cassDC

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#1323]
**What happened?**

* The podSecurityContext isn't being validated properly, I can include stuff like capabilities in this field, even though that doesn't exist on the PodSecurityContext type.
* When adding configurations to the `Container` field for the server-system-logger container, it appears that these do not propagate into the CassDC as expected.

A test demonstrating these problems can be found [here](https://github.com/k8ssandra/k8ssandra-operator/pull/1322/commits/d10271944e8e3b9295469906bbda8962933ba15d).

**Comment by burmanm** [comment]
> The image that is ending up in the sts is actually system logger instead of the vector container that should appear. This is despite vector being enabled. I'm pretty sure that means it should be a vector image instead of the system-logger image since this is the default from the struct [tags](https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/telemetry/v1alpha1/telemetry_types.go#L36) if the vector struct is non-nil.

In case this ticket gets mentioned in the release notes: This isn't correct, the server-system-logger is a docker image that bundles Vector, since cass-operator uses Vector to do the tailing (and provides the capabilities to modify how Vector is used).

One should not replace the server-system-logger image with the vector.io ones.

**Comment by Miles-Garnsey** [comment]
> In case this ticket gets mentioned in the release notes: This isn't correct, the server-system-logger is a docker image that bundles Vector, since cass-operator uses Vector to do the tailing (and provides the capabilities to modify how Vector is used).

Alex explained to me that this had been changed a while back. I didn't realised we'd started doing it this way - makes sense now he's explained it.
