### ISSUE TITLE
K8SSAND-898 ⁃ K8ssandraCluster CRD should provide a "shortName"

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#136]
**What is missing?**

Like how Cass Operator provides various short names for the `CassandraDatacenter` resource: `cassdc` `cassdcs`, something similar should be provided for the `K8ssandraCluster` resource.

**Why do we need it?**

Because typing is hard :smile:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-898) by [Unito](https://www.unito.io)
┆Reviewer: 557058:376e6d8d-84b1-46a1-a227-0887055aa65a
┆friendlyId: K8SSAND-898
┆priority: Medium

**Comment by jsanda** [comment]
I absolutely agree that we need this! Here are some suggestions:

* `kluster` - We have started using it as a variable name in code for K8ssandraCluster objects. 
* `kasscluster` - Playing off the "cass" part of `cassdc` but replace the `c` with `k` to signify k8ssandra

**Comment by emerkle826** [comment]
I prefer `kluster`, simply because it's shorter

**Comment by jeffbanks** [comment]
Is `kc` an option?

**Comment by jsanda** [comment]
I thought about `kc` as well and like it. My only reservation is if introduce and formally support a client CLI tool, I would want to call the executable `kc`.

**Comment by emerkle826** [comment]
Perhaps `k8c`?

**Comment by jdonenine** [comment]
Is there any notion of these names needing to be globally unique?  I don't know how anyone would know without a giant repository of CRDs, but what happens when we pick something that someone else did and you happen to have both installed in the same cluster?

With that said, I like `kluster` or `k8c`

**Comment by jsanda** [comment]
>Is there any notion of these names needing to be globally unique?

Good question. I'll investigate.

**Comment by bradfordcp** [comment]
I think `kc` is ripe for collision (it may not be a problem though). `k8c` is my preference if that is not available.
