### ISSUE TITLE
WATCH_NAMESPACE not properly splitting multiple namespaces

### ISSUE THREAD

**Issue by aGallea** [k8ssandra/k8ssandra-operator#1399]
**What happened?**
The operator fails to start with the following error:
```
DPANIC    setup    odd number of arguments passed as key-value pairs for logging    {"ignored key": "replicatedsecrets.replication.k8ssandra.io is forbidden: User \"system:serviceaccount:operators:k8ssandra-operator\" cannot listresource \"replicatedsecrets\" in API group \"replication.k8ssandra.io\" in the namespace \"k8ssandra-core,k8ssandra-data\""}
```
This occurs because the WATCH_NAMESPACE value (k8ssandra-core,k8ssandra-data) is treated as a single namespace instead of being split into separate namespaces.

**Did you expect to see something different?**
Operator should start without errors

**How to reproduce it (as minimally and precisely as possible)**:
1. Set the environment variable WATCH_NAMESPACE with multiple comma-separated values, for example:
```yaml
WATCH_NAMESPACE: ns1,ns2
```
2. Create a service account with the necessary RBAC roles for each namespace (ns1, ns2), ensuring the required permissions are granted.
3. Start the operator. It will fail on startup, logging an error about not being able to list resources in the combined namespace string (e.g., "ns1,ns2").

**Environment**

* K8ssandra Operator version:

    `v1.19.0`

* Kubernetes version information:

    `v1.24.17`

* Kubernetes cluster kind:

    Rancher Desktop

* Manifests:

```
insert manifests relevant to the issue
```

* K8ssandra Operator Logs:

```
INFO    setup    watch namespace configured    {"namespace": "k8ssandra-core,k8ssandra-data"}
INFO    setup    ########################### version  commit  date  ###########################
INFO    setup    manager set up with multiple namespaces    {"namespaces": "k8ssandra-core,k8ssandra-data"}
DEBUG    Finished initializing 0 client configs
INFO    controller-runtime.builder    Registering a mutating webhook    {"GVK": "k8ssandra.io/v1alpha1, Kind=K8ssandraCluster", "path": "/mutate-k8ssandra-io-v1alpha1-k8ssandracluster"}
INFO    controller-runtime.webhook    Registering webhook    {"path": "/mutate-k8ssandra-io-v1alpha1-k8ssandracluster"}
INFO    controller-runtime.builder    Registering a validating webhook    {"GVK": "k8ssandra.io/v1alpha1, Kind=K8ssandraCluster", "path": "/validate-k8ssandra-io-v1alpha1-k8ssandracluster"}
INFO    controller-runtime.webhook    Registering webhook    {"path": "/validate-k8ssandra-io-v1alpha1-k8ssandracluster"}
DPANIC    setup    odd number of arguments passed as key-value pairs for logging    {"ignored key": "replicatedsecrets.replication.k8ssandra.io is forbidden: User \"system:serviceaccount:operators:k8ssandra-operator\" cannot listresource \"replicatedsecrets\" in API group \"replication.k8ssandra.io\" in the namespace \"k8ssandra-core,k8ssandra-data\""}
```

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-249) by [Unito](https://www.unito.io)

**Comment by aGallea** [comment]
@burmanm - Looks like after merging, there is still a failing test..

**Comment by burmanm** [comment]
Looks like we have a "small" flaky issue, but it's not because of the changes here.
