### ISSUE TITLE
Multi-cluster install instructions for Mac

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#141]
**What is missing?**

The current install instructions don't appear to work as expected on MacOS. When running `setup-kind-multicluster.sh --clusters 2 --kind-worker-nodes 4` we expect to see two clusters of 4 nodes each `k8ssandra-0` and `k8ssandra-1`.

But running the above command and then `kubectl ctx` yields only one cluster:

```
kind-k8ssandra-0
```

This may be related to `getopt` on MacOS not being fully compatible with regular Linux style `getopt`. Running `getopt -T` as per the TODO note in `setup-kind-multicluster.sh ` yields:

```
getopt -T
 --
```

But installing `gnu-getopt` using brew install `gnu-getopt` doesn't seem to help, even when running `export FLAGS_GETOPT_CMD="$(brew --prefix gnu-getopt)/bin/getopt"` via `.zshrc` followed by `exec $SHELL`.

I am reluctant to run `brew link --force gnu-getopt` because that will break normal system functionality. We may need something in the script to find `gnu-getopt` and use it locally within the script only.

**Why do we need it?**

MacOS is one of the more common environments we expect to encounter.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-903) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆Fix Versions: k8ssandra-operator-1.0.0-alpha.1
┆Issue Number: K8SSAND-903
┆Priority: Medium

**Comment by Miles-Garnsey** [comment]
The problem was that there was no way to isolate the use of `gnu-getopt` to just this script. So all `getopt` calls across the whole system would be going to the GNU version. Now that may be fine, but as a user, I'm just not familiar enough with MacOS internals to know where else it is used or how MacOS default `getopt` differs to `gnu-getopt`.

This is a bit hand wavy but from a user perspective I would hesitate to switch out one of my system-standard CLI tools in order to run an install script. And adding the replacement tool to the PATH is also a bit much to ask for folks who might just be kicking the tires is also a big ask (IMO).

**Comment by adutra** [comment]
> @adutra I believe you are on a Mac. I assume you installed gnu-getopt since you have been working on the project for a little while now and are using the script. Did it cause any problems for you?

Correct, I installed gnu-getopt with Homebrew (keg only, not symlinked), then followed the instructions and added the same line as @jsanda to my `.zshrc` file:

```
export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
```

I did this many years ago and never had problems since.

I do think it would be fair to consider gnu-getopt as a required binary for k8ssandra developers.

**Comment by adejanovski** [comment]
May I ask what we're getting out of gnu-opt that would justify requiring it as a dependency?
We can achieve the same behavior at low cost and without any dependency it seems.

**Comment by jsanda** [comment]
>May I ask what we're getting out of gnu-opt that would justify requiring it as a dependency?

With the changes in #144 we have ~65 lines of code vs ~10 with the current version in main. gnu-getopt is also used in the `create-clientconfig.sh` script so there will be a similar situation there. 

I also want to point out that I tested the changes in #144 and the script changes work perfectly fine. If we decide to move forward with removing gnu-getopt, that's fine.

The bigger question/concern I have is what is the criteria we are establishing with respect to dependencies? I don't want to restrict ourselves in general though from using linux tools that might not be available out of the box in MacOS or in Windows.

**Comment by adejanovski** [comment]
> The bigger question/concern I have is what is the criteria we are establishing with respect to dependencies?

That's a very good question which I guess is a matter of weighing the benefits of introducing the dependency vs the ease of installing it (and in our case, even knowing that you need to install it).
My replacement code for removing gnu-getopt could very well be compacted to almost the same number of lines if I remove the logic to check if a value was passed for each argument, which removes some of the benefits that we're expecting from gnu-getopt: 

```
while test $# -gt 0; do
  case "$1" in
    --clusters) shift; export num_clusters=$1; shift;;
    --cluster-names) shift; export cluster_names=$1; shift;;
    --kind-node-version) shift; export kind_node_version=$1; shift;;
    --kind-worker-nodes) shift; export kind_worker_nodes=$1; shift;;
    -o|--overwrite) overwrite_clusters="yes"; shift;;
    -h|--help) help; exit;;
    --) shift; break;;
    *) break;;
  esac
done
```
