### ISSUE TITLE
Changing a DC name should be forbidden

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#1422]
There are no guardrails currently against changing the datacenter[].meta.name field in a K8ssandraCluster.

This could cause data loss and we should prevent this from happening.
Same applies to rack names (although cass-operator could prevent this already).

In any case, modifying datacenterName or datacenter[].meta.name should be forbidden by both the validation webhook and fail during reconcile.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-263) by [Unito](https://www.unito.io)
┆Fix Versions: 2024-10

**Comment by Miles-Garnsey** [comment]
I'm looking at this but I'm a bit unclear on something. The DCs are a list, so a "name change" isn't possible to distinguish from the removal of a DC... 

For example, if I wanted to remove a DC called "oldDC" but add a new one called "newDC", that isn't really a rename, it is changing the topology of the cluster, it seems to be something that users might want to do regularly....

I think the only ways to do this are;
1. make the list of DCs completely immutable after cluster creation.
2. make it only possible to add DCs after cluster creation.
3. make it possible to both add and remove DCs but not both in the same mutation.

Of these, maybe (3) is the best, but it might be hard for users to understand.

A different angle on this which might achieve the same objectives is to have a rule like "at least one DC must remain regardless of any mutations to the DC slice". 

Which do we prefer to implement here?

**Comment by Miles-Garnsey** [comment]
> A different angle on this which might achieve the same objectives is to have a rule like "at least one DC must remain regardless of any mutations to the DC slice".

Radovan likes this one, Olivier has no preference.

**Comment by burmanm** [comment]
I'll vote for 3), for reasons that it's easiest to detect in the validation but also from operational point of view as these operations are not lightweight for the cluster. Removing and decommissioning + bootstrapping another Datacenter at the same time sounds like a disaster for resource usage and network bandwidth.

**Comment by olim7t** [comment]
I vote for 3 too, it's the most practical, and I don't think the "at least one DC must remain" rule addresses the requirement.

**Comment by adejanovski** [comment]
I vote for 3 as well. I don't think we should bother checking if a rebuild is still happening in this PR (this is a timebomb as it is and we need protection asap). We can create a follow up ticket for it.

**Comment by burmanm** [comment]
From original ticket one thing:

> Same applies to rack names (although cass-operator could prevent this already).

cass-operator prevents deletion of racks, we don't have feature to do that at all: https://github.com/k8ssandra/cass-operator/issues/188

**Comment by Miles-Garnsey** [comment]
OK option (3) it is then.
