### ISSUE TITLE
K8SSAND-945 ⁃ Restructure install guide to reduce repeated content

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#179]
**What happened?**

The install guide has some repeated information in each workflow.

We also had some open questions about some of the tooling used in the examples.

**Did you expect to see something different?**

We can restructure the document some to reduce that and consolidate it into a few high-level workflows I think.  Something like:

* K8s Cluster creation
* K8s Cluster preparation (Operator Deployment)
* K8ssandraCluster deployment
* Deployment validation

We could also supplement some of the content with native kubectl examples or description of what the usability tools we're including do early in the document.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-945) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-945
┆Priority: Medium

**Comment by jsanda** [comment]
@johnsmartco I'd be happy to review the current state of things with you and answer any questions you have.
