### ISSUE TITLE
K8SSAND-1422 ⁃ k8ssandra-operator should not use clusterName directly

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra-operator#196]
**What happened?**
k8ssandra-operator has the same bug as k8ssandra & cass-operator previously. The clusterName in Cassandra has different restrictions than resourceNames in Kubernetes. All instances of ClusterName when used with resource names should be cleaned up.

See:

https://github.com/k8ssandra/k8ssandra/issues/1090
https://github.com/k8ssandra/cass-operator/pull/178

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1422) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1422
┆priority: Medium

**Comment by jsanda** [comment]
Closing this already been addressed.
