### ISSUE TITLE
K8SSAND-1073 ⁃ Expose the AllowMultipleNodesPerWorker property of the CassandraDatacenter

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#225]
**What is missing?**
`AllowMultipleNodesPerWorker` tells cass-operator relax pod anti-affinity rules such that multiple Cassandra pods can be scheduled onto the same k8s worker node.

**Why do we need it?**
This can be useful for development as well as production scenarios, particularly when there are a limited number of worker nodes.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1073) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.1.0
┆friendlyId: K8SSAND-1073
┆priority: Medium

**Comment by joebowbeer** [comment]
`podAntiAffinity` is not supported by Karpenter cluster autoscaler:

https://github.com/aws/karpenter/issues/942

Use topology spread constraints instead?

**Comment by jsanda** [comment]
This was addressed in #347.
