### ISSUE TITLE
K8SSAND-1125 ⁃ Revisit cluster name and derived resource names

### ISSUE THREAD

**Issue by adutra** [k8ssandra/k8ssandra-operator#267]
We currently have a field `CassandraClusterTemplate.Cluster` that is used to specify the Cassandra cluster name. This field is also used to create derived resource names, such as secrets, services and deployments.

But this field keeps being constantly mixed up with the `K8ssandraCluster` resource name. For example the superuser secret uses the Cassandra cluster name (because that's what cass-operator does), but Reaper secrets use the `K8ssandraCluster` name. Stargate deployments use the Cassandra cluster name, but Reaper deployments use the `K8ssandraCluster` name.

This has not been detected in tests because our tests always create `K8ssandraCluster` resources whose names are equal to the Cassandra cluster name. This confusion is present e.g. in the `RetrieveSuperuserSecret` method, where the superuser secret (created with the Cassandra cluster name) is looked up by the `K8ssandraCluster` name.

Lastly, sanitization of Cassandra cluster names is not being done optimally:

* The function `DefaultSuperuserSecretName` does a basic sanitization of the Cassandra cluster names, but the logic is not really compliant with valid DNS subdomain names as defined in RFC 1123.
* Stargate deployments are currently not sanitizing their names at all, yet the names are based on Cassandra cluster names.

Here is what I suggest:

* Remove `CassandraClusterTemplate.Cluster` completely, use `K8ssandraCluster` name consistently instead.
* CRD names must be valid DNS subdomain names, which means that, by using the `K8ssandraCluster` name, we don't need sanitizing anymore.
* If we still want to sanitize names to remove more unwanted chars (e.g. `-` is perfectly valid, but we might want to disallow it for aesthetic reasons), then create a dedicated function for that and use it consistently for creating secret, service and deployment names.
* K8ssandra Operator version: 1.0.0.-alpha3

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1125) by [Unito](https://www.unito.io)
┆Reviewer: 5e66c4695df5fb0cfee2e364
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1125
┆priority: Medium

**Comment by jsanda** [comment]
The changes sound good to me. It will simplify some things.

**Comment by burmanm** [comment]
> The function DefaultSuperuserSecretName does a basic sanitization of the Cassandra cluster names, but the logic is not really compliant with valid DNS subdomain names as defined in RFC 1123.

cass-operator creates default usernames that are always valid with DNS1035:

https://github.com/k8ssandra/cass-operator/blob/master/apis/cassandra/v1beta1/cassandradatacenter_types.go#L522

This is the restriction as placed by the Kubernetes apimachinery.
