### ISSUE TITLE
K8SSAND-1129 ⁃ Update Helm chart to support cluster-scoped deployments

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#269]
This is a place holder for https://github.com/k8ssandra/k8ssandra/issues/1235. Creating this issue since folks are most likely going to look in this repo first for anything specific to k8ssandra-operator.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1129) by [Unito](https://www.unito.io)
┆Reviewer: 5fa45931c8247300705e1fed
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1129
┆priority: Medium

**Comment by jdonenine** [comment]
This will be fixed by https://github.com/k8ssandra/k8ssandra/pull/1236
