### ISSUE TITLE
K8SSAND-1149 ⁃ Do not use client.DeleteAllOf to delete ServiceMonitors

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#279]
If we know or can compute the key for an object it is best to delete by key. ServiceMonitors however are deleted by calling `client.DeleteAllOf`.

#260 provided the initial ServiceMonitor integration for CassandraDatacenter and Stargate objects. The reconciliation logic handles deletions as follows:

```go
func (cfg PrometheusResourcer) CleanupResources(ctx context.Context, client runtimeclient.Client) error {
	if len(cfg.CommonLabels) < 1 {
		return errors.New("no labels were found to target deletion request")
	}
	if err := cfg.validate(); err != nil {
		return TelemetryConfigIncomplete{}
	}
	var deleteTargets promapi.ServiceMonitor
	err := client.DeleteAllOf(ctx,
		&deleteTargets,
		runtimeclient.InNamespace(cfg.MonitoringTargetNS),
		runtimeclient.MatchingLabels(cfg.CommonLabels),
	)
	if err != nil {
		return err
	}
	return nil
}
```

We had some back and forth discussion about the usage of `DeleteAllOf` while #260 was in flight. In fact, I initially suggested using it and then later suggested switching to `client.Delete()`. If the ServiceMonitor CRD is installed the k8s cluster, then `CleanupResources` could in fact be called frequently.

After thinking about it some more, we should be using `client.Delete()` and not `client.DeleteAllOf`. 

While this code isn't necessarily executed all the time, there are performance considerations that merit the change.  With `DeleteAllOf` I believe the api server has to fetch all ServiceMonitors in the namespace. It then does the label filtering on the client side (with respect to etcd).  Let's contrast this with doing a get followed by a delete.

There are a couple alternatives to using `DeleteAllOf`. We could simply do a `client.Delete()` to delete by key. This is slightly better but we still hit the api server every time `CleanupResources` is called. Let's consider first doing a `client.Get()`. If the ServiceMonitor doesn't exist or has already been deleted, `Get()` will return a not found error in which case there is not need to call `client.Delete()`. This is good because all reads go against the cache which means we would eliminate a lot of unnecessary calls against the api server. But what if the cache is stale? Not a problem. It can be and often is. If/when that happens it will get sorted out on a later reconciliation.

This should be done for 1.0.0.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1149) by [Unito](https://www.unito.io)
┆epic: Prometheus integration
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1149
┆priority: Medium

**Comment by Miles-Garnsey** [comment]
The formatting on my comment above is pretty horrendous, recommend reading it [here](https://k8ssandra.atlassian.net/browse/K8SSAND-1149).

**Comment by jsanda** [comment]
The typed client does hit the api server on every call to `DeleteAllOf`. Here is the full method impl:

```go
func (c *typedClient) DeleteAllOf(ctx context.Context, obj Object, opts ...DeleteAllOfOption) error {
	o, err := c.cache.getObjMeta(obj)
	if err != nil {
		return err
	}

	deleteAllOfOpts := DeleteAllOfOptions{}
	deleteAllOfOpts.ApplyOptions(opts)

	return o.Delete().
		NamespaceIfScoped(deleteAllOfOpts.ListOptions.Namespace, o.isNamespaced()).
		Resource(o.resource()).
		VersionedParams(deleteAllOfOpts.AsListOptions(), c.paramCodec).
		Body(deleteAllOfOpts.AsDeleteOptions()).
		Do(ctx).
		Error()
}
```
The `c.cache.getObjMeta(obj)` call is simply to get the type information so that it can convert from the group/version/kind (GVK) to the group/version/resource (GVR). What follows is the delete call against the api server.

`CleanupResources()` can be called frequently in some situations. Suppose the K8ssandraCluster deploys both Stargate and Reaper.  After `reconcileCassandraDCTelemetry()` is called, `reconcileStargate()` is called. The controller requeues until Stargate is ready. On each requeue, `CleanupResources()` is called again. 

Then after Stargate is ready, `reconcileReaper()` is called. Similar to Stargate the controller requeues until Reaper is ready. So on each subsequent requeue `CleanupResources()` is called again.

You might be skeptical, but I am not skeptical about the cost/performance of avoiding extra requests against the api server 😉 .  

I agree that first doing a Get is more verbose. The benefit of avoiding calls against the api server make it worthwhile though. This is the approach we take everywhere else.

**Comment by Miles-Garnsey** [comment]
> The c.cache.getObjMeta(obj) call is simply to get the type information so that it can convert from the group/version/kind (GVK) to the group/version/resource (GVR). 

Fair enough, I've dug a bit deeper and I can see you're right on this. I should have looked more closely at how the `o.Delete()` call worked before.

This means that (as you say) a cached `client.Get()` will save at least some amount of API server load, so I'll get this in my backlog.
