### ISSUE TITLE
K8SSAND-1163 ⁃ DumpClusterInfo method should provide more details

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#290]
**What is missing?**
After an e2e test runs `kubectl cluster-info` is call via the `DumpClusterInfo` method (see [here](https://github.com/k8ssandra/k8ssandra-operator/blob/main/test/framework/e2e_framework.go#L508)). The output gets uploaded in the test artifact in GHA for debugging. While it provides a lot info, there is a lot more that would be really helpful when debugging failures.

In addition to pod, deployment, etc details, `DumpClusterInfo` should provide details for the following objects:

* K8ssandraCluster
* CassandraDatacenter
* Stargate
* Reaper
* StatefulSet
* Secrets
* ReplicateSecret
* ClientConfig

**Why do we need it?**
This will help will debugging and in some cases it can hopefully speed the process up.

**Environment**

* K8ssandra Operator version:

```
1.0.0-alpha.2
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1163) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1163
┆priority: Medium

**Comment by Miles-Garnsey** [comment]
It would also be helpful to have logs for all components. Often it is the logs (rather than the resources) which allow me to diagnose an issue.
