### ISSUE TITLE
K8SSAND-1177 ⁃ Consider removing per-DC Reaper templates

### ISSUE THREAD

**Issue by adutra** [k8ssandra/k8ssandra-operator#308]
Initially reported by adejanovski here:

https://github.com/k8ssandra/k8ssandra-operator/pull/307#pullrequestreview-856321315

> I struggle to understand why we would not want to have one reaper instance per DC when deploying a multi DC cluster (which motivates this PR as kc.Spec.Reaper could not exist while Reaper is still deployed on select DCs).
> The Reaper instances work as a network, sharing their work and storage, so having them deployed with different settings seems weird and error prone. Also, not deploying them everywhere means we'll be using datacenterAvailability of LOCAL, which is less safe than EACH.
> I think we should probably simplify this and only retain the ReaperClusterTemplate while dropping the ReaperDatacenterTemplate.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1177) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1177
┆priority: Medium

**Comment by adutra** [comment]
Alternatively, if we decide eventually to keep per-DC templates, we could consider using availability ALL by default if the cluster has one single Reaper instance.

**Comment by jsanda** [comment]
Let's make decision quickly since time is short. Also keep in mind that this may impact #284. If we decide to make Reaper a cluster-wide setting, it will require additional changes for the deletion of a CassandraDatacenter. We will want to remove the Reaper instance as well (if it is deployed).

**Comment by adejanovski** [comment]
I think Alex's suggestion is the right one: by default, if we have a single Reaper instance we should use a dc availability of `ALL` instead of `LOCAL`, and `EACH` otherwise (only if we have multiple datacenters). `LOCAL`, as a less safe option, should be set knowing what you're doing instead of automatically.
That should be a simple enough change, which can totally be done post 1.0.0.

**Comment by adutra** [comment]
Just so that we are clear @adejanovski : are you then advocating for _keeping_ per-dc templates and only change the availability computation logic?

**Comment by jsanda** [comment]
If we allow per-DC, does that mean we allow some DCs to have Reaper and some not? If so, is that problematic?
