### ISSUE TITLE
K8SSAND-1181 ⁃ Upgrade Go to latest stable 1.17.x release

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#310]
**What is missing?**
We are currently on Go 1.16. 1.17.6 is currently the latest stable release.

**Why do we need it?**
We need to keep our tooling current. This should be done post-1.0.0.

**Environment**

* K8ssandra Operator version:

```
24f9ba89
```

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1181) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.1.0
┆friendlyId: K8SSAND-1181
┆priority: Medium

**Comment by burmanm** [comment]
Kubernetes json project for example will not work with go 1.16 anymore, but requires go 1.17. We might even want to skip to go 1.18 directly by the time we do the change.

**Comment by Miles-Garnsey** [comment]
Can I throw in a +1 for Michael's suggestion to move straight to Go 1.18. There are quite a few things I want to do with generics, mostly performance related.

**Comment by jsanda** [comment]
1.18 has my vote as long as it is a stable release.

**Comment by drgray20** [comment]
Hi @burmanm, could this update be done on cass-operator and reaper-operator as well, and if possible all k8ssandra repos using older Go versions.

**Comment by jsanda** [comment]
cass-operator should be updated. 

We are deprecating reaper-operator and medusa-operator and would prefer to avoid updating them if possible. After making the changes in reaper-operator and in medusa-operator we then need to update their charts in the k8ssandra repo. Then we need to update the k8ssandra chart itself. 

We are a pretty small team and this will take up what is already limited bandwidth. I think/hope time would be better spent helping folks migrate from k8ssandra 1.x to k8ssandra-operator.
