### ISSUE TITLE
K8SSAND-1188 ⁃ Fix release process for 1.0.0-alpha.3 release

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#314]
There isn't much of a release process in place right now outside of pushing the git tag to trigger the `K8ssandra Operator Release` GHA workflow which pushes the tagged image to Docker Hub.

The `config/deployments/default` kustomization declares an image transform to set the image tag for the k8ssandra-operator. It defaults to latest. For releases it should be set to the tagged version, 1.0.0-alpha.3 in this case. This will make it easier for someone wanting to install the operator via kustomize. You could simply do,

 `kubectl apply -k github.com/k8ssandra/k8ssandra-operator/config/deployments/default?ref=v1.0.0-alpha.3`

We have a bit of a chicken/egg problem at the moment. e2e tests install the operator using the `config/deployments/default` kustomization. The GHA workflows that run the e2e tests first build the operator image with a latest tag and then load the image into kind, just like we do for local development. If we push a commit or open a PR that changes the image override in `config/deployments/default`, tests will fail unless the tag is already published. 

Ideally we would wait to publish the tag until we have a good test run with the image tag change in config/deployments/default along with any other release preparation changes that are necessary.

One idea I had is to update the e2e test GHA workflows to check the branch name of the PR. If the branch is named something like `prep-release-1.0.0-alpha.3` then the workflow could easily parse the release name and create the local image tag for that in addition to the latest tag. When the PR is approved and merged, we tag from main and push the github tag so the new image tag is created and pushed to Docker Hub.

Note that I am only thinking about a short term solution at the moment since we are in effect releasing from main. Once we start creating release branches, things will have to change. I don't think there is any need though for release branches for these alpha releases.

burmanm adejanovski wdyt?

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1188) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1188
┆priority: Medium

**Comment by burmanm** [comment]
Avoiding rewrite of kustomization is somewhat simple process for e2e tests. For example, in the Makefile you have the VERSION tag and in cass-operator, this is how we build our version:

```sh
VERSION ?= 1.10.0

COMMIT := $(shell git rev-parse --short HEAD)
DATE := $(shell date +%Y%m%d)
VERSION := $(VERSION)-dev.$(COMMIT)-$(DATE)
IMG ?= $(IMAGE_TAG_BASE):$(VERSION)
```

That version is then used to tag the actual image also when building the local image (+ :latest). In the GHA, one would run the following command:

```yaml
      - name: Update kustomization to match release version for k8ssandra-operator
        id: kustChange
        shell: bash
        run: |
          $(KUSTOMIZE) edit set image controller=${IMG}
```

Of course even GHA can do the version parsing, but that's the basic principle. That way even if someone breaks it, it won't matter. 

One can modify the VERSION parsing to include tag name of course. ``TAG := $(shell git rev-parse --abbrev-ref HEAD)`` (Makefile syntax)

**Comment by burmanm** [comment]
The tag/branch process can also enforce all those names to be correct. Just do the changes and if git diff differs -> fail the release process. Or commit, whichever is better process.

**Comment by jsanda** [comment]
The e2e tests don't change the image version.

The initial and most important question is whether it is good idea to do the following steps to prepare a release:

* Create a PR that includes:
    * Change log updates
    * Any other additional doc updates
    * image tag update in `config/deployments/default`
* Modify GHA workflows for e2e tests 
    * In addition to creating `latest` image tag create one with the version specified for `config/deployments/default`
        * Note that these images are only loaded into kind for tests. They are not pushed to Docker Hub or any other registry. 
* Create and push github tag only after PR is merged

Automation of these steps is not an immediate concern. In fact, automation is irrelevant if we don't agree that this is a sound approach :)
