### ISSUE TITLE
K8SSAND-1189 ⁃ Thrift should be disabled for 3.11.x clusters

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#315]
**What happened?**
#249 introduced a structured config for cassandra.yaml. `start_rpc` was left out which makes sense. Unfortunately cass-config-definitions sets it to `true` by default. It should be disabled.

I came across this while debugging some e2e test failures the other day. Tests previously were explicitly setting `start_rpc: false` to tune things down. That's no longer possible now. Maybe this is contributing to some of the recent test flakes.

**Did you expect to see something different?**

Thrift should be turned off, or we should expose it and turn it off be default. Right now, it is enabled and the user cannot disable it. This should be fixed for 1.0.0.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-1189) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1189
┆priority: Medium

**Comment by Miles-Garnsey** [comment]
I wouldn't mind taking this on if you haven't started it @jsanda. I don't know anything about how the cassandra.yaml configuration object works, but there's plenty of examples in the code for me to figure it out I think.

**Comment by jdonenine** [comment]
I think that works @Miles-Garnsey, unless @adejanovski you think this will cause a lot of conflict with the work you've still got going on in any way?

Assuming not, @adejanovski could you help @Miles-Garnsey with getting this fix rolling?

**Comment by adejanovski** [comment]
I don't think it would conflict with my current work.
My recommendation would be to set `start_rpc` to false explicitly somewhere in `config.go`.
