### ISSUE TITLE
Investigate how to reconcile across remote clusters

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#32]
# Background
A controller is initialized with client to the api server. By default the client reads from a cache and writes directly to the api server. The controllers sets up watches in order to get event notifications. When the cache is updated with some event, an informer calls the appropriate event handler. The event handler adds the object to a work queue where it will later be reconciled. Note that events in the queue will be deduplicated.

See this [diagram](https://github.com/kubernetes/sample-controller/blob/master/docs/controller-client-go.md) for a great architectural overview of how this all works. We are working with controller-runtime which provides some abstractions and layers on top of some of the components in the diagram.

Let's look at some code snippets to see how things are initialized with controller-runtime. The first thing that we do is create a `Manager`:

```go
	mgr, err := ctrl.NewManager(ctrl.GetConfigOrDie(), ctrl.Options{
		Scheme:                 scheme,
		MetricsBindAddress:     metricsAddr,
		Port:                   9443,
		HealthProbeBindAddress: probeAddr,
		LeaderElection:         enableLeaderElection,
		LeaderElectionID:       "dcabfccc.k8ssandra.io",
		Namespace:              watchNamespace,
	})
```

The `Manager` does several things including,

* Create api server client
* Initialize the cache
* Manage lifecycle of controllers (starting/stopping) 

Next we initialize our controller(s):

```go
	if err = (&controllers.K8ssandraClusterReconciler{
		Client: mgr.GetClient(),
		Scheme: mgr.GetScheme(),
	}).SetupWithManager(mgr); err != nil {
		setupLog.Error(err, "unable to create controller", "controller", "K8ssandraCluster")
		os.Exit(1)
	}
```

Several things happen when `SetupWithManager` is called including,

* The controller is created
* The `K8ssandraClusterReconciler` is initialized.
  * This is basically the controller callback function that handles events 
* Event handlers are registered
  * These handlers add objects (more specifically, `reconcile.Request`) to the work queue
  * `reconcile.Request` is just a wrapper around `types.NamespacedName`

The k8ssandra cluster controller (or k8ssandra controller for short) is the control plane. Let's further assume we only want it to run in the control plane cluster. cass-operator needs to run in the data plane, i.e., remote clusters where the CassandraDatacenters and Cassandra pods will be deployed

A control plane cluster can also be part of the data plane. For example we could create a multi-DC Cassandra cluster with a DC running in each of two k8s clusters. One of the k8s clusters would be designated as the control plane, and this is where the k8ssandra controller will run.

# Problem
The k8ssandra controller needs to create objects (namely CassandraDatacenters) in remote clusters. A client that reads directly from and writes directly to the api server will suffice for this. We already use this type of client in integration and e2e tests. 

The k8ssandra controller will need to perform orchestration across the remote clusters above and beyond creating objects. This basically means we need a controller for each remote cluster.

When we receive an event notification for an object from any given cluster we would like to have the corresponding object added to a single, shared work queue. Remember that by default each controller has its own work queue.

Why do we want a single work queue? The reconciler function works off of a single queue. If we can aggregate events from remote clusters into a single queue, then we process them with a single reconciler function. This was the approach taken in [multicluster-controller](https://github.com/admiraltyio/multicluster-controller).

We can create a work queue and configure the controller to use it instead of having one created when we call `SetupWithManager`. We could create this queue in advance of creating any controllers and initialize each controller with the queue.

The Controller expects `reconcile.Request`s to be stored on the queue. In addition to the namespace and the name of the object we also need to know the source cluster from which the event originated.

When the controller pops an item from the queue, it calls its `reconcilerHandler` method (see the full source [here](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.3/pkg/internal/controller/controller.go#L274). It then casts the object to a `reconcile.Request` as shown below:

```go
func (c *Controller) reconcileHandler(ctx context.Context, obj interface{}) {
	// Update metrics after processing each item
	reconcileStartTS := time.Now()
	defer func() {
		c.updateMetrics(time.Since(reconcileStartTS))
	}()

	// Make sure that the the object is a valid request.
	req, ok := obj.(reconcile.Request)
	if !ok {
		// As the item in the workqueue is actually invalid, we call
		// Forget here else we'd go into a loop of attempting to
		// process a work item that is invalid.
		c.Queue.Forget(obj)
		c.Log.Error(nil, "Queue item was not a Request", "type", fmt.Sprintf("%T", obj), "value", obj)
		// Return true, don't take a break
		return
	}
        ....
}
```

This case is problematic since we need to store a different object type on the work queue.  I have been reviewing controller-runtime and this appears to be the big issue we need to work around. There are well-defined interfaces in controller-runtime. `Controller` is one of them (see [here](https://github.com/kubernetes-sigs/controller-runtime/blob/v0.8.3/pkg/controller/controller.go#L61)). I would like to reuse as much as possible without having to completely new implementations of some of the core controller-runtime types.

# Other Questions
Aside from figuring out how best to store the necessary information in the work queue there are some other questions we need to address.

**Should we consider something other than the kubernetes api for communication between the control plane and remote clusters?**

We could deploy an agent that runs in each remote cluster. It could run a controller in the local cluster and provide a gRPC API for example that the control plane would use.

**What is needed to run a controller for a remote cluster?**
We know for example that we need a cache with informers and event handlers. We do not need another Manager instance. Hopefully we can avoid another work queue.

**Could source.Channel be an option?**
controller-runtime sets watches on a `source.Source` which is an interface for a source of events. `source.Kind` is an implementation for events that originate in-cluster. `source.Channel` is a source of events that originate out of cluster.

Event handlers can be registered for multiple `Source`s with single controller. Each source with utilize the controller's work queue.

┆Issue is synchronized with this [Jiraserver Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-661) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-661
┆Priority: Medium

**Comment by cscetbon** [comment]
@jsanda it would be great to have a diagram that shows clearly the choice made. you're talking about one queue on each remote cluster but not sure how it gets connected to the remote controller. Cause they read from one queue as well, so does it mean it's the same, do you mean it gets copied from one queue to the other ? and how do you confirm the change has actually been made ?

**Comment by jsanda** [comment]
I would like to use one queue across controllers (controllers for the same kind that is), similar to what Admirality did. I would also like to reuse as much of the controller-runtime as possible without having to provide alternative implementations. The challenge with a shared queue is that the objects it stores would need to include a field to identify the source cluster. The `reconcileHandler` function from controller-runtime that I described above won't allow that.

I will definitely provide some diagrams :)

**Comment by cscetbon** [comment]
@jsanda it got closed somehow

**Comment by burmanm** [comment]
I think the closing was intentional as that feature is implemented (although not documented).

**Comment by cscetbon** [comment]
Can you add some links ? There should be a link to a PR at least, thanks

**Comment by burmanm** [comment]
PR #51 Added it to the tests. Basically, it adds new Watches to the same manager and then adds those as sources to the controller. In that way, the shutdown / start sequence is the same for all target clusters and all the clusters will push the same events to the same queue which is triggering the same instance of Reconcile function.

**Comment by jsanda** [comment]
I am going to create a separate ticket to document the approach we have taken, but I want to provide a brief summary here to wrap up this ticket.

#55 added a ClientConfig CRD that is basically a wrapper around a kubeconfig secret. At start up we fetch all ClientConfig objects and create a client for each k8s context. We then we create a `cluster.Cluster` object (from controller-runtime).  

Note that creating the client connection may be redundant since we can get a client from the `cluster.Cluster` object, but that is for another discussion.

We then add each `cluster.Cluster` to the Manager.  

When we initialize `K8ssandraClusterReconciler` in its `SetupWithManager` method we add watches as follows:

```go
	cb := ctrl.NewControllerManagedBy(mgr).
		For(&api.K8ssandraCluster{}, builder.WithPredicates(predicate.GenerationChangedPredicate{}))
...
	for _, c := range clusters {
		cb = cb.Watches(source.NewKindWithCache(&cassdcapi.CassandraDatacenter{}, c.GetCache()),
			handler.EnqueueRequestsFromMapFunc(clusterLabelFilter))
		cb = cb.Watches(source.NewKindWithCache(&api.Stargate{}, c.GetCache()),
			handler.EnqueueRequestsFromMapFunc(clusterLabelFilter))
	} 
```

`source.NewKindWithCache` allows us to create the watch using the cache from the remote `cluster.Cluster`. In order to get notifications, we need a `EnqueueRequestsFromMapFunc` that enqueue a reconcile request for the K8ssandraCluster object. This is accomplished with `clusterLabelFilter`:

```go
	clusterLabelFilter := func(mapObj client.Object) []reconcile.Request {
		requests := make([]reconcile.Request, 0)
		labels := mapObj.GetLabels()
		cluster, found := labels[api.K8ssandraClusterLabel]
		if found {
			requests = append(requests, reconcile.Request{NamespacedName: types.NamespacedName{Namespace: mapObj.GetNamespace(), Name: cluster}})
		}
		return requests
	}
```

In #66 I updated the controller to add the `K8ssandraClusterLabel` label to the CassandraDatacenter and Stargate objects that it creates. The label specifies the name of the K8ssandraCluster. This provides the necessary information to create the reconciliation request.

Right now the assumption is that everything is deployed in the same namespace across all clusters. With some modifications we should be able to support deploying in different namespaces across clusters.
