### ISSUE TITLE
K8SSAND-1203 ⁃ Expose AllowMultipleWorkersPerNode from CassandraDatacenter spec

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#342]
**What is missing?**
The `AllowMultipleWorkersPerNode` allows multiple C* pods to be co-located on the same k8s worker node.

**Why do we need it?**
There are times during dev/testing when it is convenient to be able to co-locate C* pods particularly if there are a limited number of worker nodes. Some folks may use this for production deployments as well.

**Environment**

* K8ssandra Operator version:

    `Insert image tag or Git SHA here`
    
    **Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1203) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1203
┆priority: Medium

**Comment by jsanda** [comment]
Yeah I got that backwards. TBH, I am not a fan either name (or the incorrect one). CassKop has a property named `HardAntiAffinity`. That is more clear IMO especially after looking at the Kubernetes [docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity). 

What do you think about `HardPodAntiAffinity`?

**Comment by Miles-Garnsey** [comment]
I definitely agree that we should be using k8s terminology which better describes the underlying mechanism of what we're doing. 

The only "problem" is that if we call it `HardPodAntiAffinity` we need to flip the bool between the representation in the K8ssandraDatacenter CRD and the CassandraDatacenter CRD. I don't know if that influences our decision...

**Comment by jsanda** [comment]
cass-operator defaults to hard, pod anti-affinity. I could see where flipping could lead to confusion and/or bugs. What about `SoftPodAntiAffinity`? The default would be consistent with cass-operator's default behavior.

**Comment by Miles-Garnsey** [comment]
> What about SoftPodAntiAffinity?

Why didn't I think of that! I'll update my PR with your suggestion there, thanks!
