### ISSUE TITLE
K8SSAND-1215 ⁃ Add encryption support to Medusa

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#354]
**What is missing?**
When encryption is turned on, Cassandra, Stargate and Reaper will all get configured appropriately but Medusa won't.
We need to configure Medusa appropriately to support client to node encryption.

**Why do we need it?**
Encrypted clusters still need to be backed up ;)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1215) by [Unito](https://www.unito.io)
┆fixVersions: k8ssandra-operator-v1.1.0
┆friendlyId: K8SSAND-1215
┆priority: Medium

**Comment by adejanovski** [comment]
@bradfordcp, I'd like to prioritize this as we've had requests for it and Medusa is the only component that won't work if encryption is enabled.
wdyt?

**Comment by jsanda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/354?planning-poker) with ZenHub @adejanovski @jeffbanks
