### ISSUE TITLE
K8SSAND-1221 ⁃ CreateMultiStargateAndDatacenter e2e test is flaky

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#361]
**What happened?**
I have been seeing the CreateMultiStargateAndDatacenter e2e test fail intermittently across different PRs lately. The last failure I looked at failed with this from GHA logs:

```
Error:     stargate_apis_test.go:25: test Stargate native API in context kind-k8ssandra-0
=== RUN   TestOperator/CreateMultiStargateAndDatacenter/TestStargateApis[0]/TestStargateRestApi
Error:     stargate_apis_test.go:29: test Stargate REST API in context kind-k8ssandra-0
=== RUN   TestOperator/CreateMultiStargateAndDatacenter/TestStargateApis[0]/TestStargateRestApi/TestSchemaApi
    stargate_apis_test.go:107: 
        	Error Trace:	stargate_apis_test.go:107
        	            				stargate_apis_test.go:59
        	            				stargate_apis_test.go:39
        	Error:      	Not equal: 
        	            	expected: 201
        	            	actual  : 500
        	Test:       	TestOperator/CreateMultiStargateAndDatacenter/TestStargateApis[0]/TestStargateRestApi/TestSchemaApi
        	Messages:   	Expected create table request to return 201
=== RUN   TestOperator/CreateMultiStargateAndDatacenter/TestStargateApis[0]/TestStargateRestApi/TestDocumentApi
```
The test failed in the `createKeyspaceAndTableRest` function trying to create a table. One of the Stargate pod logs reported a WriteTimeoutException. Prior to creating the table, the function creates the keyspace. It does this in a `require.Eventually` call. We should do the same for creating the table. It will have to be a bit different than what is done for keyspace creation.

Making a POST request against the keyspaces endpoint returns a 201 even if the keyspace already exists. Making a POST request against the tables endpoint returns a 400 if the table already exists. We need to check if the table exists before trying to create it.

**Environment**

* K8ssandra Operator version:

    v0.4.0

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-1221) by [Unito](https://www.unito.io)
┆affectedVersions: k8ssandra-operator-v1.0.0
┆fixVersions: k8ssandra-operator-v1.0.0
┆friendlyId: K8SSAND-1221
┆priority: Medium

**Comment by jsanda** [comment]
This is similar to or maybe duplicate of #337. We sporadically see failures in some of the Stargate API calls. I think a lot of this is due to running with limited resources. Providing retry logic for these API calls may provide some more stability. I started doing this in #362.

**Comment by adutra** [comment]
> Making a POST request against the tables endpoint returns a 400 if the table already exists. 

I double-checked that and it turns out that the endpoint returns 200 if the table already exists. This is simply because the statement has an `IF NOT EXISTS` clause:

https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/7acc28c87db2c9979ab7a94df452082fd612440f/management-api-agent-common/src/main/java/com/datastax/mgmtapi/NodeOpsProvider.java#L512

**Comment by adutra** [comment]
Sorry about my previous post, I was looking at management-api instead of Stargate... I probably needed more ☕ .

Anyways, Stargate does return 201 when successful, and 400 for an existing table. I think we can turn that 400 into a regular 201 by adding `"ifNotExists": true` to the payload.
