### ISSUE TITLE
K8SSAND-1243 ⁃ k8ssandra-operator can't be installed due to annotation size

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#396]
When installing the control plane as show in the docs using `kubectl apply -k github.com/k8ssandra/k8ssandra-operator/config/deployments/control-plane`, it fails with the following error message:

```
The CustomResourceDefinition "k8ssandraclusters.k8ssandra.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

The same problem happens when using ArgoCD to perform the installation.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-1243) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1243
┆priority: Medium

**Comment by adutra** [comment]
You need to use server-side apply:

```
kubectl apply --server-side -k github.com/k8ssandra/k8ssandra-operator/config/deployments/control-plane
```

We did that already for the e2e tests, but there might be places in the docs where we are still using client-side apply.

**Comment by adejanovski** [comment]
There doesn't seem to be any workaround but server side apply indeed. With ArgoCD it means ticking the "Replace" box, which is probably fine as it's going to be for the operator installation only, not the creation of K8ssandraCluster objects.
The install docs all include the use of server side apply already, so we're fine.
@bradfordcp @jsanda, we could use this ticket to write a short blog post showing how to deploy K8ssandra-operator with ArgoCD, which would include the gotcha on using the "Replace" option. wdyt?

**Comment by jsanda** [comment]
Blog post or FAQ sounds good to me

**Comment by jsanda** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/396?planning-poker) with ZenHub @adejanovski @adutra

**Comment by bradfordcp** [comment]
Let's close this ticket then and open a new one that's appropriately scoped. Do you have any links to share regarding server side apply?

**Comment by adejanovski** [comment]
@bradfordcp, here's a link on server-side apply: https://kubernetes.io/docs/reference/using-api/server-side-apply/
