### ISSUE TITLE
K8SSAND-1262 ⁃ Investigate whether tests risk being run on non-test clusters

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#420]
**(EDIT: under investigation, John thinks there are mitigations already in place.)**

**What happened?**

I have seen some strange issues when running the e2e tests while also working on other clusters. In some cases, I've received errors that the K8ssandraCluster CRD does not exist. This raises the question of whether some e2e test functions may be running against the other clusters I'm working on, rather than the test clusters they should be running against.

**Did you expect to see something different?**

All kubectl commands used in the e2e tests should explicitly use a test cluster (kind-k8ssandra-0). 

**How to reproduce it (as minimally and precisely as possible)**:

```
kind delete cluster --name k8ssandra-0 && kind delete cluster --name k8ssandra-1 && make e2e-setup-multi
kubectl config use-context <ANOTHER_CLUSTER_YOU_OWN>
make E2E_TEST=TestOperator/ClusterScoped/MultiDcMultiCluster e2e-test
```

Observe whether new resources are created on `ANOTHER_CLUSTER_YOU_OWN` (obviously, please don't reproduce this with an important cluster).

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1262) by [Unito](https://www.unito.io)
┆Reviewer: Miles Garnsey
┆friendlyId: K8SSAND-1262
┆priority: Medium

**Comment by jsanda** [comment]
@Miles-Garnsey you are indeed right. I tried a simple test of removing my `~/.kube/config` file and running a test. It failed miserably. The problem is where we call `kubectl`.

**Comment by Miles-Garnsey** [comment]
We really need a test to detect when this happens as it could damage prod clusters in the wild. I don't think we can do that as long as we're using GHA though, because

1. We need 3 clusters (and we're struggling with capacity with 2).
2. We are 'testing the test suite' which is obviously going to be more compute intensive.

Maybe we need to talk again about where we're running these tests...

**Comment by jsanda** [comment]
>We really need a test to detect when this happens as it could damage prod clusters in the wild.

What exactly would this test detect? Keep in mind that as eventually add support for running tests against arbitrary clusters, we will likely want to use `~/.kube/config`. 

>Another thing we should do: the kubectl methods aren't currently attached to a struct, we ought to attach them to a struct to ensure that any call to kubectl has a context specified. That would really help us avoid the multiple places where we have to define which context we're operating in.

With the changes I introduced in #424 we always set `--kubeconfig=build/kubeconfig` which only includes contexts for the kind clusters.

**Comment by Miles-Garnsey** [comment]
> What exactly would this test detect? Keep in mind that as eventually add support for running tests against arbitrary clusters, we will likely want to use ~/.kube/config.

I was just thinking we could include a third dummy entry in the kubeconfig, maybe a mocked up API server in a goroutine.

Then the procedure would be-
1. Set the mock api server using `kubectl config use-context`.
2. Run the tests.
3. Keep the mock server running throughout and check at the end of the tests if it has received traffic. 
4. If it has, fail.

We may eventually want to use remote clusters for testing, but in either event we probably to stay away from `/.kube/config` at all times, and force the user to create a kubeconfig in the project directory or `./build` similarly to the way it works currently.

> With the changes I introduced in https://github.com/k8ssandra/k8ssandra-operator/pull/424 we always set --kubeconfig=build/kubeconfig which only includes contexts for the kind clusters.

I took a quick look at that, the approach you've taken wasn't the first one that came to mind for me, but it looks like it'll add a lot of safety!

I still think it is worth adding a test for this however, given that it could cause some quite severe issues.

**Comment by Miles-Garnsey** [comment]
I've just been trying to run some concurrent tests both locally and remotely, I have found that the current makefile targets are still hitting my remote cluster to install cert-manager and traefik. This causes a failure in both tests.

It appears that we still have various issues around the use of the default kubeconfig file, at least in the makefiles.

**Comment by Miles-Garnsey** [comment]
We have discussed this and from recollection I was asked not to fix it. @jsanda can you confirm that you want things to remain as they are? If not, I will re-open.

**Comment by jsanda** [comment]
I'm good with things as is mostly because I would put this at the bottom of the queue in terms of priority.
