### ISSUE TITLE
K8SSAND-1265 ⁃ Document ClientConfigs

### ISSUE THREAD

**Issue by jdonenine** [k8ssandra/k8ssandra-operator#427]
**What is missing?**
Provide baseline documentation outlining the concept of the ClientConfigs what they are comprised of, used for, and how they can be generated from an existing context using the provided scripts.

**Why do we need it?**
So that users can understand the concept of how communication is enabled between clusters.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1265) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1265
┆priority: Medium

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/427?planning-poker) with ZenHub @jsanda @jeffbanks @adejanovski

**Comment by jeffbanks** [comment]
Possible duplicate for this one on ticket [#436](https://app.zenhub.com/workspaces/k8ssandra-grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/436)

**Comment by bradfordcp** [comment]
Good eye @jeffbanks. I closed #436

**Comment by jsanda** [comment]
This is already documented in https://github.com/k8ssandra/k8ssandra-operator/tree/main/docs/remote-k8s-access, but we need to update the docs in the k8ssandra repo. Created https://github.com/k8ssandra/k8ssandra/issues/1427.
