### ISSUE TITLE
K8SSAND-1310 ⁃ kuttl test always use the "latest" tag

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#449]
kuttl tests reference the `latest` tag but the deployment will use the tag referenced in the default kustomization.yaml file, which for a release branch will be the future release number.
This results in failing kuttl tests for each release that we try to cut.

The kuttl tests automation should instead parse the `newTag` value in the kustomization file and use it to build the image that will get loaded into kind.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1310) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1310
┆priority: Medium

**Comment by jsanda** [comment]
We use a kustomize overlay so that we always use `latest`, even on the release branch. 

I am closing since this is actually consistent with what we do in e2e tests in terms of the tag used.
