### ISSUE TITLE
K8SSAND-1318 ⁃ Helm install docs are missing step to add K8ssandra helm repo

### ISSUE THREAD

**Issue by KiaFarhang** [k8ssandra/k8ssandra-operator#459]
**What happened?**

Running through [the local single-cluster Helm install docs](https://docs-v2.k8ssandra.io/install/local/single-cluster-helm/) I got an error when running the command to install the k8ssandra-operator helm chart:

```
helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --create-namespace
```

I hadn't added the k8ssandra helm repo, because there's no step in the v2 docs that say to do so.

It looks like [the v1 docs](https://github.com/k8ssandra/k8ssandra/blob/main/docs/content/en/install/local/_index.md#configure-the-k8ssandra-helm-repository) _do_ list this information, and running `helm repo add k8ssandra https://helm.k8ssandra.io/stable` is all I needed to do for the install to work.

**Did you expect to see something different?**

We should list the steps for adding the k8ssandra helm repo to the operator installation docs before telling users to perform the helm install.

**How to reproduce it (as minimally and precisely as possible)**:

`helm repo remove k8ssandra`
`helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --create-namespace`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1318) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1318
┆priority: Medium

**Comment by johnsmartco** [comment]
Fixing in https://github.com/k8ssandra/k8ssandra/pull/1349.

**Comment by johnsmartco** [comment]
Done
