### ISSUE TITLE
K8SSAND-1322 ⁃ Make fixtures cloud-ready

### ISSUE THREAD

**Issue by adutra** [k8ssandra/k8ssandra-operator#463]
Currently storage class names are set to `standard` in fixture files, and racks are set to `rack1`, `rack2` etc.. 

This won't work if we execute the tests in the cloud. The test is going to fail though because storage classes will vary from cluster to cluster, and such zones do not exist.

We need to add kustomization for storage class names, racks, and maybe more.

This could be done with a new `-storageClass` flag, or maybe with something more future-proof, e.g. `-cloudProvider GKE`.

We'll need to keep in mind that storage classes can be provided at 2 levels:

* cluster-level: `spec.cassandra.storageConfig.cassandraDataVolumeClaimSpec.storageClassName`
* dc-level: `spec.cassandra.datacenters.storageConfig.cassandraDataVolumeClaimSpec.storageClassName`

This makes the usage of yq even more appealing (see #462).

_Originally posted by @jsanda in_ [_https://github.com/k8ssandra/k8ssandra-operator/pull/446#pullrequestreview-907495606_](https://github.com/k8ssandra/k8ssandra-operator/pull/446#pullrequestreview-907495606)

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1322) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1322
┆priority: Medium

**Comment by jsanda** [comment]
@bradfordcp I want draw your attention to this as we need to be running tests against cloud providers even if its an ad hoc thing that isn't part of the GHA workflows.

@adutra can you please provide a poker planning estimate?

**Comment by adutra** [comment]
@jsanda and @bradfordcp I strongly suggest that we implement #515 first. This is because the biggest issue when moving tests to cloud providers is how to test external APIs. With #515, we would make it easier to change the Ingress controller, and hide Ingress implementation details from the e2e tests. We also need to figure out what to do with raw TCP ingresses to test the CQL port.

I estimated #515 to 3. Once that is done, I also estimate the remaining effort to execute e2e tests in cloud providers to 3.

**Comment by adutra** [comment]
FYI #515 should be merged today, and after some investigation today I already have a path forward regarding ingress, including CQL port. So I'm lowering my estimate to 2 for this ticket since there are no more unknowns.
