### ISSUE TITLE
K8SSAND-1336 ⁃ Doc: Tasks > Secure topic needs review and updates for K8ssandra Operator

### ISSUE THREAD

**Issue by johnsmartco** [k8ssandra/k8ssandra-operator#474]
**What happened?**

"K8ssandra security" topic at https://docs-v2.k8ssandra.io/tasks/secure/ is just a copy of the v1.4.x topic.  Needs review and updates from an engineer to revise the info for K8ssandra Operator. 

**How to reproduce it (as minimally and precisely as possible)**:

* https://github.com/k8ssandra/k8ssandra/blob/docs-v2/docs/content/en/tasks/secure/_index.md
* https://docs-v2.k8ssandra.io/tasks/secure/

**K8ssandra Operator version**
1.0.x.

**Anything else we need to know?**:

* Revise the topic on the `doc-v2` branch of k8ssandra/k8ssandra GH repo. 
* When ready, remove the `{{ tbs }}` shortcode that imports a heads-up Note for users.
* When done and PR is merged, please tag and publish the updates. Tag & publish steps: https://github.com/k8ssandra/k8ssandra/tree/docs#github-actions-and-tags

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1336) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1336
┆priority: Medium

**Comment by adejanovski** [comment]
Replaced by a corresponding ticket in the k8ssandra project: #1370

**Comment by adejanovski** [comment]
Handled here: https://github.com/k8ssandra/k8ssandra/issues/1370
