### ISSUE TITLE
K8SSAND-1339 ⁃ Doc: Tasks > Repair topic needs review and updates for K8ssandra Operator multi-cluster

### ISSUE THREAD

**Issue by johnsmartco** [k8ssandra/k8ssandra-operator#477]
**What happened?**

The "Repair Cassandra with Reaper" topic at https://docs-v2.k8ssandra.io/tasks/manage/private-registries/ is just a copy of the v1.4.x topic.  Need a SW engineer to review and update the content for K8ssandra Operator multi-cluster. 

**How to reproduce it (as minimally and precisely as possible)**:

* https://github.com/k8ssandra/k8ssandra/blob/docs-v2/docs/content/en/tasks/repair/_index.md
* https://docs-v2.k8ssandra.io/tasks/repair/

**K8ssandra Operator version**
1.0.x.

**Anything else we need to know?**:

* Revise the topic on the `doc-v2` branch of k8ssandra/k8ssandra GH repo. 
* When done and PR is merged, please tag and publish the updates. Tag & publish steps: https://github.com/k8ssandra/k8ssandra/tree/docs#github-actions-and-tags

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1339) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1339
┆priority: Medium

**Comment by adejanovski** [comment]
Handled in the k8ssandra project: https://github.com/k8ssandra/k8ssandra/issues/1368
