### ISSUE TITLE
K8SSAND-1342 ⁃ Doc: Tasks > Migrate topic should include info from K8ssandra Operator multi-cluster migration *blog post*

### ISSUE THREAD

**Issue by johnsmartco** [k8ssandra/k8ssandra-operator#480]
## Bug Report
**Describe the bug**
The topic at https://docs-v2.k8ssandra.io/tasks/migrate was copied from K8ssandra v1.4.x docs.  To fix, use content from Alex adejanovski 's blog that describes the steps to migrate from a K8ssandra 1.4.x cluster to a K8ssandra Operator multi-cluster.

**To Reproduce**

* Blog URL TBS.
* https://github.com/k8ssandra/k8ssandra/blob/docs-v2/docs/content/en/tasks/migrate/_index.md
* https://docs-v2.k8ssandra.io/tasks/migrate/

**Anything else we need to know?**:

* Revise the topic on the `doc-v2` branch of k8ssandra/k8ssandra GH repo. 
* When ready, remove the `{{ tbs }}` shortcode that imports a heads-up Note for users. 
* When done and PR is merged, please tag and publish the updates. Tag & publish steps: https://github.com/k8ssandra/k8ssandra/tree/docs#github-actions-and-tags

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1342) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1342
┆priority: Medium

**Comment by adejanovski** [comment]
@bradfordcp, following our discussion, I reworked the K8ssandra-operator migration blog post to update the migrate task documentation page for v2 docs: https://github.com/k8ssandra/k8ssandra/compare/docs-v2...upgrade-v2-migrate-docs?expand=1

As I'm out next week, feel free to do any change that seems necessary on the branch and move forward with this ticket.
