### ISSUE TITLE
K8SSAND-1359 ⁃ Document removing a datacenter from an existing cluster

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#488]
#284 added support for removing a DC from an existing cluster. We need to document what is involved with the process.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1359) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1359
┆priority: Medium

**Comment by bradfordcp** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/488?planning-poker) with ZenHub @Miles-Garnsey @jsanda @burmanm

**Comment by Miles-Garnsey** [comment]
I can't help here, sorry. On my estimate it would be a 3 day research task, but someone else will be able to estimate it without that step I think.

**Comment by jsanda** [comment]
This is a duplicate of #441.
