### ISSUE TITLE
K8SSAND-1365 ⁃ Delete remote backups when a MedusaBackup object is deleted

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#494]
**Is your feature request related to a problem? Please describe.**
If I create a MedusaBackupJob, that causes a backup operator to be performed by Medusa on each of the Cassandra nodes. Backups are stored in remote storage, e.g., an S3 bucket, and a corresponding MedusaBackup object is created in Kubernetes. If I delete the MedusaBackup object, the backup files are orphaned in the S3 bucket.

**Describe the solution you'd like**
k8ssandra-operator should add a finalizer to the MedusaBackup object. Kubernetes will block deletion of the MedusaBackup until the finalizer is cleared. The backup controller should clear the finalizer after the backup has been removed from remote storage. Medusa's gRPC API provides a DeleteBackup operation which makes the necessary calls to delete the backup from remote storage.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1365) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1365
┆priority: Medium

**Comment by jsanda** [comment]
This should be addressed by #492.

**Comment by adejanovski** [comment]
Do you want to close this as duplicate?

**Comment by adejanovski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-60a54d01d464160012441e2f/issues/k8ssandra/k8ssandra-operator/494?planning-poker) with ZenHub @adutra @burmanm @jeffbanks
