### ISSUE TITLE
K8SSAND-1367 ⁃ Allow overriding cluster names to enable non DNS compatible ones

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#496]
K8ssandra-operator uses the `meta.Name` value as cluster name for the generated cassdc objects.
Since `meta.Name` values are restricted to formats that are DNS compatible, it prevents the migration from external clusters that use spaces or uppercase letters in their names.

We'd need to provide an override for cluster names that aren't compliant, under the CassandraClusterTemplate and CassandraDatacenterTemplate.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1367) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1367
┆priority: Medium

**Comment by bradfordcp** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/496?planning-poker) with ZenHub @adejanovski

**Comment by bradfordcp** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/496?planning-poker) with ZenHub @jsanda
