### ISSUE TITLE
K8SSAND-1408 ⁃ Value encoded does not coincide with the commented value

### ISSUE THREAD

**Issue by DGerich** [k8ssandra/k8ssandra-operator#499]
expected: reaper-ui
encoded: reaper-jmx

https://github.com/k8ssandra/k8ssandra-operator/blob/fcafb69659aac8cc2339c9077a5ded98621a2d46/test/testdata/fixtures/multi-dc-encryption-reaper/k8ssandra.yaml#L17

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1408) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1408
┆priority: Medium

**Comment by adejanovski** [comment]
Hi @DGerich,

It's indeed not the right value that's encoded there, not that it fails any test but for correctness sake, we need to update it.

thanks, and well spotted :)
