### ISSUE TITLE
K8SSAND-1468 ⁃ num_tokens cannot be set

### ISSUE THREAD

**Issue by sinohC** [k8ssandra/k8ssandra-operator#530]
Hi all!

I'm trying to deploy cassandra 3.11.7 cluster using the latest k8ssandra-operator. 
Setting the num_tokens value in the cassandra config won't do anything, but if I don't set that property the default (256) is set correctly and the cluster is deployed succesfully.

They way I'm setting the value:

![imagen](https://user-images.githubusercontent.com/48013777/164517438-bd6ea7fb-cab3-4a37-b7ab-662b57c5d820.png)

I'm actually using k8ssandra-operator 1.0.2 and kubernetes v1.20.11.

I'm doing something wrong? or is it a bug? 

Thanks in advance!

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1468) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1468
┆priority: Medium

**Comment by jsanda** [comment]
There is test coverage of the webhook around `num_tokens` (see [here](https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/k8ssandra/v1alpha1/k8ssandracluster_webhook_test.go#L205)). It should be updated as part of the fix since it didn't catch this bug as it should have.

**Comment by jsanda** [comment]
@sinohC The fix for this will be available in the upcoming 1.1 release.
