### ISSUE TITLE
K8SSAND-1473 ⁃ StargateSpec configuration for JWT authorization with external authentication

### ISSUE THREAD

**Issue by caniko** [k8ssandra/k8ssandra-operator#531]
**What is missing?**
I am in great need of JWT authorization with external authentication, and I have voiced this earlier in 2021 in the K8ssandra repository, https://github.com/k8ssandra/k8ssandra/issues/1158. K8ssandra operator also doesn't [expose JAVA_OPTS](https://github.com/k8ssandra/k8ssandra/issues/1179), which would be a fine workaround for now. Moreover, it is a very crude implementation, and these fields should be exposed natively to the manifest.

I think @dougwettlaufer is more educated than me on this topic. Refer to this [post](https://github.com/stargate/docs/issues/201#issuecomment-1086776419) to learn about requirements for JWT authorization with external authentication on Stargate; semi-verified [example](https://github.com/stargate/docs/issues/201#issuecomment-1108851023). Fields under `JAVA_OPTS` that should be exposed:
- `-D stargate.auth_id` (this will be set to `AuthJwtService` in my case)
- `-D stargate.auth.jwt_provider_url`, JWKS URL
- ~`-D stargate.cql_use_transitional_auth` (`true` when authentication is upstream)~

**Why do we need it?**
This is a natively supported feature by Stargate, and it should be supported along with other native Stargate features. JWT has advantages over password authentication, the main benefit is the reduced load on the IDP -> lowered latency -> faster uploads.

**Environment**

* K8ssandra Operator version:

```
Name:                   k8ssandra-operator
Namespace:              k8ssandra
CreationTimestamp:      Sat, 23 Apr 2022 21:56:46 +0200
Labels:                 app.kubernetes.io/instance=k8ssandra-operator
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=k8ssandra-operator
app.kubernetes.io/part-of=k8ssandra-k8ssandra-operator-k8ssandra
control-plane=k8ssandra-operator
helm.sh/chart=k8ssandra-operator-0.37.1
Annotations:            deployment.kubernetes.io/revision: 1
meta.helm.sh/release-name: k8ssandra-operator
meta.helm.sh/release-namespace: k8ssandra
Selector:               app.kubernetes.io/instance=k8ssandra-operator,app.kubernetes.io/name=k8ssandra-operator,app.kubernetes.io/part-of=k8ssandra-k8ssandra-operator-k8ssandra,control-plane=k8ssandra-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
Labels:           app.kubernetes.io/instance=k8ssandra-operator
app.kubernetes.io/managed-by=Helm
app.kubernetes.io/name=k8ssandra-operator
app.kubernetes.io/part-of=k8ssandra-k8ssandra-operator-k8ssandra
control-plane=k8ssandra-operator
helm.sh/chart=k8ssandra-operator-0.37.1
Service Account:  k8ssandra-operator
Containers:
k8ssandra-operator:
Image:      docker.io/k8ssandra/k8ssandra-operator:v1.0.1
Port:       9443/TCP
Host Port:  0/TCP
Command:
/manager
Liveness:   http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
Readiness:  http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
Environment:
WATCH_NAMESPACE:           (v1:metadata.namespace)
K8SSANDRA_CONTROL_PLANE:  true
Mounts:
/controller_manager_config.yaml from manager-config (rw,path="controller_manager_config.yaml")
/tmp/k8s-webhook-server/serving-certs from cert (ro)
Volumes:
manager-config:
Type:      ConfigMap (a volume populated by a ConfigMap)
Name:      k8ssandra-operator-manager-config
Optional:  false
cert:
Type:        Secret (a volume populated by a Secret)
SecretName:  k8ssandra-operator-webhook-server-cert
Optional:    false
Conditions:
Type           Status  Reason
----           ------  ------
Available      True    MinimumReplicasAvailable
Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   k8ssandra-operator-6894cf5cdd (1/1 replicas created)
Events:
Type    Reason             Age   From                   Message
----    ------             ----  ----                   -------
Normal  ScalingReplicaSet  32m   deployment-controller  Scaled up replica set k8ssandra-operator-6894cf5cdd to 1
```

**Anything else we need to know?**:
Academic project

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1473) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1473
┆priority: Medium

**Comment by adutra** [comment]
@bradfordcp @jsanda I think this is indeed something we should provide.

**Comment by caniko** [comment]
I did some digging.

[Function](https://github.com/k8ssandra/k8ssandra-operator/blob/763fe12b5e2e822329074f3373b53a9a8941b604/pkg/stargate/deployments.go#L321) where `JAVA OPTS` config is set. [Where](https://github.com/k8ssandra/k8ssandra-operator/blob/763fe12b5e2e822329074f3373b53a9a8941b604/pkg/stargate/deployments.go#L174) function output is applied.

**Comment by jsanda** [comment]
@caniko am I correct in thinking the changes needed are exposing the `stargate.auth_id` and the `stargate.auth.jwt_provider_url` JVM system properties?

I agree that there should be explicit properties for them vs passing them through in JAVA_OPTS.

**Comment by jsanda** [comment]
@adutra do want to take this?

**Comment by caniko** [comment]
> @caniko am I correct in thinking the changes needed are exposing the `stargate.auth_id` and the `stargate.auth.jwt_provider_url` JVM system properties?
> 
> I agree that there should be explicit properties for them vs passing them through in JAVA_OPTS.

Yes, I can do some tests in June.
