### ISSUE TITLE
K8SSAND-1514 ⁃ e2e tests on branches should run against the version of the operator being released

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#549]
**Problem**
e2e tests are configured to always run against the `latest` image version of the operator, even on release branches. The cluster scoped test(s) are not configured to run against `latest` on release branches. These tests will fail prior to release since they are trying to pull images that are not yet available. 

**Solution**
I opened #548 which adds an overlay to run the cluster scoped test against a `latest` version. There is a better, simpler solution. Update the GHA workflow to parse the image version from `config/deployments/default/kustomization.yaml`. Create the tag locally  just like we do for `latest` and then load the image tag into the kind clusters. This completely eliminates the need for an additional overlay.

**Environment**

* K8ssandra Operator version:

    `1.0.2`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1514) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1514
┆priority: Medium

**Comment by adejanovski** [comment]
I'd like to suggest using a tool such as [bump2version](https://pypi.org/project/bump2version/) which allows to bump the version in multiple files at once, following a version pattern that we can define.
The tool requires to define a set of files that need to be updated in the codebase when performing a version bump, and invoking the tool can be done with `bump2version major/minor/patch`. It takes care of making the changes where necessary and creating a commit. An example cfg file can be found [here](https://github.com/thelastpickle/cassandra-medusa/blob/master/.bumpversion.cfg) in the Medusa project.

This would involve that we stop using `latest` as our working version number, and trade it for `x.x.x-dev` versions (or something alike). We can still push a `latest` tag when we build the `main` branch.
The kustomization file would be updated during upgrades as well as a newly introduced `VERSION` file that wouldn't require error prone parsing and would be usable by all tests to select the version to install.
