### ISSUE TITLE
K8SSAND-1524 ⁃ Add a resource configuration block for every spawned POD

### ISSUE THREAD

**Issue by andrey-dubnik** [k8ssandra/k8ssandra-operator#553]
**What is missing?**

Configuration for the resources for the PODs managed by the operator

**Why do we need it?**

The best practice is to set resource requirements for every POD running to allow the correct resource placement. 

> Also our operations team require every resource deployed (via the admission controller) to have such configuration otherwise it is rejected by the policy.

**Environment**

* K8ssandra Operator version: v1.1.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1524) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1524
┆priority: Medium

**Comment by jsanda** [comment]
I agree that container resources need to be configurable. I read some interesting stuff earlier today that suggests it could be a bad idea to set limits. See https://www.reddit.com/r/kubernetes/comments/all1vg/on_kubernetes_cpu_limits/. With that said, I do think they should be configurable.

**Comment by andrey-dubnik** [comment]
Just got into the issue while enabling Reaper as reaper deployment does not have resources defined. 

Behaviour is following:
1. Operator is stuck in Deploying forever without throwing any errors
2. Once limit enforcement is suspended on the gatekeeper Reaper is able to proceed

There are 2 issues linked to that 
1. Operator likely should have some sort of error handling/log trail to handle the faulty deployments of the Reaper resource (maybe a new issue?)
2. We should be able to control the limits of PODs (current issue)

**Comment by adejanovski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/553?planning-poker) with ZenHub @jsanda @Miles-Garnsey

**Comment by adejanovski** [comment]
@jsanda @bradfordcp, I think we have enough info to move forward and estimate that ticket. I think we should be able to implement this before v1.2 ships out. wdyt?

**Comment by jsanda** [comment]
I agree that this would be a nice enhancement for 1.2.

**Comment by adejanovski** [comment]
We may want to set request defaults as well while we implement these changes.

**Comment by Miles-Garnsey** [comment]
A few things here as I'm looking to pick this up. 

* I think the original scope needs revision. We probably want resources blocks for every spawned **container** - pods don't have resource blocks.
* Do we want initContainers to also have resource blocks? I think yes since the motivation is to ensure that they can be scheduled in systems where a validating webhook rejects requests for containers without resource limits. 
* But if we do include initContainers, this is a very broad ticket. Maybe we should do containers first? In either event, I suggest we make this an epic and ticket it out pod by pod to keep PR sizes more manageable.

**Comment by adejanovski** [comment]
> I think the original scope needs revision. We probably want resources blocks for every spawned container - pods don't have resource blocks.

Agreed

> Do we want initContainers to also have resource blocks? I think yes since the motivation is to ensure that they can be scheduled in systems where a validating webhook rejects requests for containers without resource limits.
But if we do include initContainers, this is a very broad ticket. Maybe we should do containers first? In either event, I suggest we make this an epic and ticket it out pod by pod to keep PR sizes more manageable.

Interesting question. If that's going to be more involved, I agree that we should separate concerns and create a follow up ticket for init containers 👍

**Comment by jsanda** [comment]
I don't think the motivation is to be able to have a webhook to reject pods without limits. This ticket is about exposing the resources APIs for containers and init containers created by the operator. It would be good to see proposed API changes first. I don't think exposing resources for init containers makes this more complicated, does it?

**Comment by Miles-Garnsey** [comment]
> I don't think exposing resources for init containers makes this more complicated, does it?

No, just a larger blast radius, but the work for initContainers/Containers is equivalent as far as I can see.

**Comment by adejanovski** [comment]
Well, if you need to be able to set distinct resource requirements for every specific init container we have, it makes it more involved for sure (and it'll make more CRD changes as well).
@Miles-Garnsey, I'm ok with making this an epic and creating sub tickets per pods. It'll allow to track work more efficiently and create smaller PRs.
