### ISSUE TITLE
K8SSAND-1558 ⁃ Declare securityContext with runAsUser and group in reaper deployment 

### ISSUE THREAD

**Issue by mapster** [k8ssandra/k8ssandra-operator#564]
**Is your feature request related to a problem? Please describe.**
Pod Security Policies with runAsUser and runAsGroup will modify the securityContext of the pods so that they match an applicable policy. Since the Reaper Deployment doesn't have a securityContext, the pod admission controller will [mutate](https://kubernetes.io/docs/concepts/policy/pod-security-policy/#policy-order) the pods with the minimum allowd uid/gid of the first (alphabetically) applicable policy. The reaper container must run as uid:gid 1001:1001 due to file ownerships in the container. 

**Describe the solution you'd like**
Add a securityContext to the Reaper Deployment with `runAsUser: 1001` and `runAsGroup: 1001`.

**Describe alternatives you've considered**
Another solution is to have a unique service account associated with the pods, so that cluster administrators can assign a specific pod security policy to the pods that have `runAsUser: 1001` and `runAsGroup: 1001`

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1558) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1558
┆priority: Medium

**Comment by jsanda** [comment]
With k8ssandra-operator the security context is already configurable. I just created https://github.com/k8ssandra/k8ssandra-operator/issues/583 to address using the default service account. I am going to close this since this is covered in k8ssandra-operator with the addition of the new ticket.
