### ISSUE TITLE
K8SSAND-1564 ⁃ Ability to specify limits.cpu,limits.memory for all pod containers

### ISSUE THREAD

**Issue by abbeny** [k8ssandra/k8ssandra-operator#568]
**What is missing?**

I'am trying to install K8ssandra-operator  in  multi-tenant Kubernetes but not working by default.
I add different modifications in the chart to start to play with k8ssandra.

I got some errors like: 

```
statefulset-controller  create Pod cassandra2-dc1-default-sts-0 in StatefulSet cassandra2-dc1-default-sts failed error: pods "cassandra2-dc1-default-sts-0" is forbidden: failed quota: kaas-compute-resources-cassandra-preprod: must specify limits.cpu,limits.memory 
```

and more ...

What do you think if you can add : 

* More flexibility to set and modify limits.cpu,limits.memory for all pod containers. 
* Add sidecar to k8ssandracluster with possibility to mount secrets and configmaps as volumes.
* Add support External-DNS
* Make more support for the old version of kubernetes like Kubernetes v1.20

**Why do we need it?**

I think  these features will be appreciated by the community.

**Environment**
Tested in Kubernetes v1.19

**Anything else we need to know?**:

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1564) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1564
┆priority: Medium

**Comment by adejanovski** [comment]
> More flexibility to set and modify limits.cpu,limits.memory for all pod containers.

This is possible already at least for Cassandra and Stargate: https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/k8ssandra/v1alpha1/k8ssandracluster_types.go#L279 and https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/stargate/v1alpha1/stargate_types.go#L57
I reckon it's currently missing for Reaper. There's another issue for that specific need: https://github.com/k8ssandra/k8ssandra-operator/issues/553

> Add sidecar to k8ssandracluster with possibility to mount secrets and configmaps as volumes.

While this is possible in cass-operator, we're not yet exposing the podTemplateSpec in k8ssandra-operator. We definitely plan on doing so and I'll create a ticket to track this.

> Make more support for the old version of kubernetes like Kubernetes v1.20

That's more problematic as cass-operator v1.11.0 (which is needed for various other components) now requires k8s v1.21 😕 
If I may ask, could you create an issue [in the cass-operator](https://github.com/k8ssandra/cass-operator/issues) project asking to bring back support for 1.19/1.20?
We'll see if that can be done or not.

**Comment by jsanda** [comment]
@abbeny there is already https://github.com/k8ssandra/k8ssandra-operator/issues/556 for dealing with secrets. With respect to ConfigMaps, what is your use case?

**Comment by jsanda** [comment]
@abbeny what do you want to see in k8ssandra-operator with respect to external-dns?

It is worth noting that cass-operator 1.10.x does support older versions of kubernetes. Right now there isn't much divergence between the latest release 1.11.0 and 1.10.x. We could explore continuing to backport changes to 1.10.x in order to support older k8s versions.

Please create a feature request for adding custom, user-defined containers to the K8ssandraCluster. This has come up multiple times. It would be good to get a issue created for it.

**Comment by adejanovski** [comment]
> Please create a feature request for adding custom, user-defined containers to the K8ssandraCluster. This has come up multiple times. It would be good to get a issue created for it.

@jsanda, we already have https://github.com/k8ssandra/k8ssandra-operator/issues/569 for that.

**Comment by adejanovski** [comment]
I think the requested additions here should be covered by: #569 (container injection), #501 (labels and annotations which should allow supporting external-dns), #553 (setting resources requests/limits for each created pod)

The only thing that remains is whether or not we could support k8s v1.20 in cass-operator. I'll open a ticket for it in cass-operator's repo and we should be able to close this ticket.

**Comment by adejanovski** [comment]
I've created the issue in cass-operator: https://github.com/k8ssandra/cass-operator/issues/352

@abbeny, does it look to you like we're covering your requests with these tickets?

**Comment by abbeny** [comment]
@adejanovski @jsanda, yes awesome, thank's for your responsiveness.
