### ISSUE TITLE
K8SSAND-1579 ⁃ Add metric filters support to exclude unwanted metrics.

### ISSUE THREAD

**Issue by prasus** [k8ssandra/k8ssandra-operator#573]
**What is missing?**

The k8ssandra 1.x allows to configure [metric_filters](https://github.com/k8ssandra/k8ssandra/blob/main/charts/k8ssandra/values.yaml#L428) by which we can exclude unwanted metrics, This feature is net yet there the k8ssandra-operator which is a limiting factor as it causes issues as explained below. 

**Why do we need it?**

We recently noticed a weird thing after enabling Prometheus metrics in the k8ssandra cluster managed by the operator, The `/metrics` endpoint (`e.g http://<cassandra-pod-ip>:9103/metrics`) is way too big, around 31 MB on a 9 node cluster! :scream:

```
curl -LO http://10.244.45.116:9103/metrics                                       
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 31.0M    0 18844    0     0  17502      0  0:30:59  0:00:01  0:30:58 17627
```

This is abnormal and it causes excessive network traffic on the minion that runs Prometheus leading to congestion and performance issues, we had to disable Prometheus monitoring for our k8ssandra clusters due to this :slightly_frowning_face: 

**Environment:**

Kubernetes v1.21.4 (self hosted)

**K8ssandra Operator version:**

k8ssandra-operator v1.1.1

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1579) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1579
┆priority: Medium

**Comment by adejanovski** [comment]
We definitely dropped the ball here. We should add the ability to define metrics filters in the telemetry sections of the CRD.
Cassandra does spit out a whole lot of metrics, which can get unmanageable if you have lots of tables.
I'll move this into our backlog so we can schedule work on it, unless you're willing to contribute here? In this case we'd be more than happy to provide guidance.

FTR, this is done by passing the filters as an env variable in the Cassandra containers, which can be defined directly [in the cassdc object definition](https://github.com/k8ssandra/k8ssandra/commit/c70db562b79ee088b7cdc15e0079598de2474b4d#diff-300c6ee64b50bfc7daa74e968fbef8ecb63180e1a85555d49912f0f743f7bab3R298-R313).
The metrics filters would have to be added as an array [in the telemetry api](https://github.com/k8ssandra/k8ssandra-operator/blob/main/apis/telemetry/v1alpha1/telemetry_types.go) and converted into the above referenced env variable.

**Comment by adejanovski** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/K8ssandra-Grooming-623b197f1fcd4800110540ef/issues/k8ssandra/k8ssandra-operator/573?planning-poker) with ZenHub @Miles-Garnsey @adutra
