### ISSUE TITLE
K8SSAND-1607 ⁃ Materialized views

### ISSUE THREAD

**Issue by caniko** [k8ssandra/k8ssandra-operator#590]
**What is missing?**
The functionality in stargate outlined in this [issue](https://github.com/stargate/docker-images/issues/105) from Stargate.

**Why do we need it?**
Toggle materialized views in K8ssandra-operated Cassandra clusters.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1607) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1607
┆priority: Medium

**Comment by jsanda** [comment]
This should already be possible today. It is already possible to supply a cassandra.yaml for Stargate via a ConfigMap. We do this in e2e tests. Note the `cassandraConfigMapRef` field [here](https://github.com/k8ssandra/k8ssandra-operator/blob/79c5ffc8f366d55f247b2071baab349423bd3734/test/testdata/fixtures/multi-dc-stargate/k8ssandra.yaml#L114-L114). 

Feel free to reopen if this doesn't address your needs.
