### ISSUE TITLE
K8SSAND-1614 ⁃ ServiceMonitor causes double scraping, and double values

### ISSUE THREAD

**Issue by flokli** [k8ssandra/k8ssandra-operator#597]
**What happened?**
I created a `CassandraDatacenter` CR, that sets `spec.cassandra.prometheus.enabled` to `true`.

`k8ssandra-operator`/ `k8ssandra-operator-cass-operator` creates the a `${cassandraDatacenter}-cass-servicemonitor` `ServiceMonitor` resource.

However, that `ServiceMonitor` resource seems to be targeting both the `${cassandraDatacenter}-service` and `${cassandraDatacenter}-all-pods-service`. As the name of the `Service` resource being scraped usually is part of the time series, this will double the amounts of metric series to be scraped, and will cause some metrics to display double the values.

**Did you expect to see something different?**
I'd expect the `ServiceMonitor` to only scrape one of the two services. Considering the `*-all-pods-service` has a `cassandra.datastax.com/prom-metrics=true` label, that should probably be part of the selector in the `ServiceMonitor` resource.

**How to reproduce it (as minimally and precisely as possible)**:
Create a `CassandraDatacenter` with  `spec.cassandra.prometheus.enabled` to `true`, and check what services the `ServiceMonitor` is targeting.

**Environment**

* K8ssandra Operator version: docker.io/k8ssandra/k8ssandra-operator:v1.0.1
* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:

EKS

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1614) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1614
┆priority: Medium

**Comment by adejanovski** [comment]
@Miles-Garnsey, would you mind taking a look at this issue? wdyt?

**Comment by Miles-Garnsey** [comment]
@flokli your comments here are entirely accurate:

> I'd expect the ServiceMonitor to only scrape one of the two services. Considering the *-all-pods-service has a cassandra.datastax.com/prom-metrics=true label, that should probably be part of the selector in the ServiceMonitor resource.

This is my mistake and I've raised a PR [here](https://github.com/k8ssandra/k8ssandra-operator/pull/610) to address it. It didn't click for me that there were two services and that was why `cassandra.datastax.com/prom-metrics=true` was required in the ServiceMonitor selector.
