### ISSUE TITLE
K8SSAND-1624 ⁃ Design the required annotations for the internal secrets provider

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#606]
The internal secrets provider webhook will get its information from annotations that will be placed on pods.
We need to design which annotations will be supported by the webhook in order to mount and format the secrets appropriately.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1624) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1624
┆priority: Medium

**Comment by Miles-Garnsey** [comment]
@sseidman while reviewing your PR #798 we've realised that we don't quite have consensus on how the annotations should look. 

We have a few options as present; 

1. Your existing format  e.g. `k8ssandra.io/inject-secret-<SECRETNAME>: <MOUNTLOCATION>`.
2. Something that better delineates what parts of the string are values from what parts are values e.g. `k8ssandra.io/inject-secret,secretName=a,path=b` or (maybe better as it puts all values in the value of the annotation) `k8ssandra.io/inject-secret: secretName=a,path=b`
3. Use standard json for the value e.g. `k8ssandra.io/inject-secret: {"secretName": "a", "path": "b"}`

Are you open to one of the second two options? Are there any considerations we need to be aware of from your side in this space?

Personally, I'm OK with either option 2 or 3. My only concern about using json is that I don't know how it will look (from a readability standpoint) once we take into  account any escaping required for the double quotes.

**Comment by adejanovski** [comment]
FWIW, there doesn't seem to be any escaping in the JSON stored in annotations:

![Capture d’écran 2023-01-05 à 07 34 15](https://user-images.githubusercontent.com/5096002/210716856-842eff22-edb2-41e6-a35f-729c33aa05c7.png)

Above is how it looks like on K8ssandraCluster objects. We already use json for replication settings and Kubernetes uses it for the last applied configuration.

**Comment by adejanovski** [comment]
We'll never store passwords themselves in the annotations, so we're fine here 😉

**Comment by Miles-Garnsey** [comment]
> We'll never store passwords themselves in the annotations, so we're fine here 😉

Uh, true, I wasn't thinking. And we shouldn't usually see any directory names or secret names with those characters. So we should be fine indeed.

**Comment by sseidman** [comment]
Hey sorry for the late reply, been a busy week. I think as far as the suggestions go what we liked about our initial approach was that it was simple and reads well, but as far as cons go, it is not extensible and requires multiple annotations for multiple secrets, which I can see being an issue.

I think we like the third suggestion as it allows for the dict (`{"secretName": "a", "path": "b"}`) to be extended with additional fields if needed. I think the one adjustment we would like to make is that it be an array of dicts if possible, e.g.:
```
k8ssandra.io/inject-secret: [{"secretA": "a", "path": "b"}, {"secretB": "a", "path": "b"}]
```
so that multiple secrets can be injected if needed. How does that sound?

**Comment by adejanovski** [comment]
Hi @sseidman, you're proposal looks great. I chatted offline with @Miles-Garnsey who agrees as well.
Let's roll with it 👍
