### ISSUE TITLE
More E2E tests for Prometheus integrations

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#611]
**What is missing?**

More E2E tests for Prometheus integration.

**Why do we need it?**

Issue #597 identified that we were double scraping Prometheus metrics because we were picking up two separate CassDC attached services.

While the immediate bug is resolved under PR #610 it did highlight that we lack E2E tests which fully exercise the Prometheus integration's we've built. 

The current tests only confirm that the SMs are deployed. They do not test that the various metrics we expect to see are indeed present, or that they are flowing through into Prometheus in the way we expect.

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/K8OP-188) by [Unito](https://www.unito.io)
┆Issue Number: K8OP-188

**Comment by jsanda** [comment]
We have the `Test_NewCassServiceMonitor_SUCCESS` unit test (see [here](https://github.com/k8ssandra/k8ssandra-operator/blob/d50191e301bba4d313015023d4199059f8dbd09b/pkg/telemetry/prom_cass_servicemonitor_test.go#L12-L12)) which only performs this check against the created ServiceMonitor:

```go
assert.Equal(t, "prometheus", actualSM.Spec.Endpoints[0].Port)
```
Shouldn't the test verify the full state, including both metadata and the spec?

We also have the `createSingleDatacenter` integration test which checks that the ServiceMonitor is created and deleted (see [here](https://github.com/k8ssandra/k8ssandra-operator/blob/d50191e301bba4d313015023d4199059f8dbd09b/controllers/k8ssandra/k8ssandracluster_controller_test.go#L252-L252)). We should probably do additional verification here. We should also have coverage in a multi-DC/cluster test.
