### ISSUE TITLE
K8SSAND-1631 ⁃ Document default filters for MCAC in the telemetry CRD

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#612]
Default filters are applied for MCAC if none is provided, matching what was done in K8ssandra v1. These need to be documented in the CRD.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1631) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1631
┆priority: Medium

**Comment by jsanda** [comment]
I followed up to my [comment](https://github.com/k8ssandra/k8ssandra-operator/pull/588#discussion_r915132755) in #588. The pointer to the slice ticks the boxes for supporting the 3 behaviors. 

The only other thing that needs to be addressed from my perspective is documenting the defaults.
