### ISSUE TITLE
K8SSAND-1700 ⁃ Nil pointer exception when auth is disabled

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#637]
**What happened?**

When I create a cluster with `auth` enabled, then disable it, I see a NPE and the operator crashes.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start a k8ssandracluster with no auth defined at all.
1. Switch to auth being explicitly disabled.
1. I think the operator crashes here.
1. If you didn’t get a crash in (3) try deleting the cluster. That was the last thing I did before I recall seeing chaos.

** K8ssandra Operator version: **

1.2.0

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1700) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1700
┆priority: Medium

**Comment by Miles-Garnsey** [comment]
Here is a log of the nil pointer dereference we see: [k8ssandra-operator-75d64456d8-cs5jm.log](https://github.com/k8ssandra/k8ssandra-operator/files/9205358/k8ssandra-operator-75d64456d8-cs5jm.log)

Having reproduced this, I can confirm that you don't need to delete the pod, you simply add `spec.auth: false` and the NPE occurs.

**Comment by Miles-Garnsey** [comment]
I've narrowed down to a few areas. The main one is [here](https://github.com/k8ssandra/k8ssandra-operator/blob/main/pkg/telemetry/cassandra_metrics_filters.go#L41), when auth is disabled, the PodTemplateSpec is nil and we get an NPE on the attempt to access `dcConfig.PodTemplateSpec.Spec.Containers[containerIndex].Env`.

It seemed there was also a problem [here](https://github.com/k8ssandra/k8ssandra-operator/blob/main/pkg/cassandra/datacenter.go#L432), there was no guard against `dcPodTemplateSpec` being passed in nil, which then again NPEs.

**Comment by jsanda** [comment]
Fixed in #640
