### ISSUE TITLE
K8SSAND-1722 ⁃ cassandra.DatacenterConfig.PodTemplateSpec should be a value type

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#645]
**What happened?**

The meaning of the field `cassandra.DatacenterConfig.PodTemplateSpec` has changed over the course of development and it is no longer optimal to type this field as a pointer.

A pointer field in a struct is always optional, which necessitates a large number of nil checks throughout the codebase. When functions mutate the DatacenterConfig in the wrong order (without an initialised PodTemplateSpec) nil pointer errors can easily occur. 

Because reconciliation logic now relies heavily on always having a PodTemplateSpec available for mutation, it is optimal to enforce this by making the field a value type. 

For an example of the kinds of problems that occur with the current type see [this issue](https://github.com/k8ssandra/k8ssandra-operator/issues/637).

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1722) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1722
┆priority: Medium

**Comment by adutra** [comment]
Fixed by #784.
