### ISSUE TITLE
Update Stargate e2e tests to check api access

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#65]
The e2e tests just check that Stargate becomes ready. We should also check the following:

* Verify that the auth endpoint is reachable
* Generate an auth token
* Perform CRUD operations with the various apis (document, graphql, etc.)

The integration tests in the k8ssandra repo already do a lot of this. Those tests configure ingress with traefik. Rather than install  traefik with helm I think it would be good if we could deploy it via kustomize since we already use kustomize in the tests. This [article](https://blog.tomarrell.com/post/traefik_v2_on_kubernetes) demonstrates how to deploy traefik with kustomize.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-781) by [Unito](https://www.unito.io)
┆Epic: Stargate Controller Integration
┆Fix Versions: k8ssandra-2.0.0-beta
┆Issue Number: K8SSAND-781
┆Priority: Medium

**Comment by jdonenine** [comment]
So, generally yes, except that I'd say this on is focused on implementing them in automated fashion.  What I put in after we all met the other day in K8SSAND-821 was just to get any form of testing in place - manual would be fine for that for now.

If we want to go after the automation now, that's great, and we can then scrap 821.

That make sense?
