### ISSUE TITLE
K8SSAND-1733 ⁃ Remove PreserveUnknownFields from K8ssandraCluster CRD

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#652]
**What is missing?**

The `CassandraDatacenterTemplate` type is declared with the kubebuilder annotation `//+kubebuilder:pruning:PreserveUnknownFields`, which leads to lighter touch OpenAPI validation on the type. This should be removed if possible.

**Why do we need it?**

Invalid fields can be added to a CR without triggering an error, which leads to a poor user experience when those fields then cause silent reconciliation failures.

See [here](https://github.com/k8ssandra/k8ssandra-operator/issues/647#issuecomment-1210890425) for an example.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1733) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1733
┆priority: Medium

**Comment by Miles-Garnsey** [comment]
I have started work to make this change, however it appears to trigger a NPE. I need to dig more deeply into why.

**Comment by adejanovski** [comment]
Hi @Miles-Garnsey, any updates on this ticket? Do you need help to get this done?

**Comment by Miles-Garnsey** [comment]
Hi @Miles-Garnsey, any updates on this ticket? Do you need help to get this done?

Yep, I'd been asking for a while but figured it was de-prioritised. I don't know how to move forward on it given the huge number of failures we get on removing the tag.

**Comment by adutra** [comment]
I found the culprit: if you remove the annotation, [this patch](https://github.com/k8ssandra/k8ssandra-operator/blob/main/config/crd/patches/remove_config_validation.json) gets applied and removes everything in the config.

We need to remove this patch completely. See the work I'm doing in #703.

**Comment by Miles-Garnsey** [comment]
I'm not sure why that would cause all of the unit test failures I observed, unit tests don't normally touch the kustomize patches?

**Comment by adutra** [comment]
The "integration tests" (aka testEnv tests) do, since they install all the CRDs. Other unit tests are OK on my end, which failures are you seeing?

**Comment by Miles-Garnsey** [comment]
I was seeing failures on my PR over here, the logs are all gone though. I think I should close that PR if you have this working over on your branch :) 

https://github.com/k8ssandra/k8ssandra-operator/pull/653

**Comment by adutra** [comment]
At this point I'm confident you can close your PR. This will be fixed as part of #710, PR to follow shortly.
