### ISSUE TITLE
K8SSAND-1763 ⁃ Operator should not allow rack name change of a live cluster

### ISSUE THREAD

**Issue by maximethebault** [k8ssandra/k8ssandra-operator#667]
**What is missing?**

Changing the rack name of a live cluster (and thus changing the NetworkTopology) is unsupported.
The operator should reflect that and explicitely block this operation.
Instead, it tries to carry out this change and new Cassandra replicas display such errors:

```
INFO  [main] 2022-09-03 17:22:43,469 NetworkTopologyStrategy.java:88 - Configured datacenter replicas are dc1:rf(3)
ERROR [main] 2022-09-03 17:22:43,472 CassandraDaemon.java:911 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Token allocation failed: the number of racks 2 in datacenter dc1 is lower than its replication factor 3.
```

**Why do we need it?**

Protect from accidental changes
Make the operator safer to use

**Environment**

* K8ssandra Operator version: 1.2.0

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1763) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1763
┆priority: Medium

**Comment by adejanovski** [comment]
I agree that rack changes shouldn't be allowed in live datacenters. Any such change should be done by migrating to a new datacenter that uses the required rack assignments. Even if it were done in a way that Cassandra accepts, this could lead to data loss (or at least reduce the consistency guarantees).
We should treat this the same way we do with attempts to change the number of tokens, prevent it both in the validating webhook and in the K8ssandraCluster reconcile.
The same check should probably be done in cass-operator too.

**Comment by burmanm** [comment]
cass-operator already prevents renaming racks:

https://github.com/k8ssandra/cass-operator/blob/master/apis/cassandra/v1beta1/cassandradatacenter_webhook.go#L189

There's an open ticket to allow removing a rack, which is not supported at the moment. Adding racks is a supported feature.

**Comment by adejanovski** [comment]
cool, all we need is to add that check in k8ssandra-operator as well then.

**Comment by jsanda** [comment]
I talked with @olim7t and we agree that there are other situations where we will want similar, duplicate validation checks. He is going to investigate to see if we can minimize that duplication.

**Comment by olim7t** [comment]
After more discussion with the team, we are not convinced anymore that duplicating the validation logic is a good solution. It's not just rack names, there are many more things being checked by cass-operator. The two controllers operate on different structs so it is hard to minimize the duplication.

With the current version of the code, any validation error in cass-operator will be reported in the `Status.Error` field of the `K8ssandraCluster`, which makes it pretty visible to the user.

**Comment by adejanovski** [comment]
@maximethebault, looking at the original ticket description, it doesn't seem like what you've done is a rack name change but rather removing a rack.
The error message you're seeing suggests that:

```
ERROR [main] 2022-09-03 17:22:43,472 CassandraDaemon.java:911 - Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: Token allocation failed: the number of racks 2 in datacenter dc1 is lower than its replication factor 3.
```

Could you confirm?

**Comment by maximethebault** [comment]
@adejanovski Sorry for the late reply, missed the notification.

I had the error during a rack name change. I posted more details here: https://discord.com/channels/836217371453685760/836217371453685763/1015677950869381230

Note that in the discord messages, I added a rack configuration to a cluster that had none defined (I guess in this case a rack is created implicitly), but I can reproduce the exact same issue by changing the name of an explicitly defined rack.

**Comment by adejanovski** [comment]
This is no longer possible in the latest versions.
I tried to follow the steps you described on Discord and this is what I get:

```
2022-12-19T07:22:22.837Z	ERROR	Reconciler error	{"controller": "k8ssandracluster", "controllerGroup": "k8ssandra.io", "controllerKind": "K8ssandraCluster", "K8ssandraCluster": {"name":"cluster","namespace":"k8ssandra-operator"}, "namespace": "k8ssandra-operator", "name": "cluster", "reconcileID": "a7d279cb-b1b1-4ac1-8c25-8c15a065ed9c", "error": "admission webhook \"vcassandradatacenter.kb.io\" denied the request: CassandraDatacenter write rejected, attempted to change rack name from 'default' to 'r1'"}
```

**Comment by adejanovski** [comment]
I'll go ahead and close this issue.
Feel free to reopen if you can reproduce this in the latest release.

**Comment by maximethebault** [comment]
For reasons completely unrelated to K8ssandra, I'm unfortunately stuck at v1.2.1 atm, but I'll make sure to test it out as soon as I can.
Merci!
