### ISSUE TITLE
K8SSAND-1779 ⁃ Upgrade to Go 1.18 and to operator-sdk 1.23

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#681]
**What is missing?**
We are still on Go 1.17.  Our Kubernetes dependencies are on 1.23.4. Based on [here](https://github.com/k8ssandra/k8ssandra-operator/blob/main/Makefile#L347) in the Makefile it looks like we are on operator-sdk v1.18.0. Going through the [upgrade guide](https://sdk.operatorframework.io/docs/upgrading-sdk-version/) up through the latest release, which is v1.23.0, will move us to Go 1.18, update Kubernetes dependencies to 1.24, and update tooling dependencies like controller-gen.

For reference these changes have already been made in cass-operator in https://github.com/k8ssandra/cass-operator/pull/399.

@burmanm A couple questions for you:

* In https://github.com/k8ssandra/cass-operator/issues/398 you mentioned upgrading to Kustomize 4.5.7 for performance improvement and the ability to use newer namespace transformer to remove some hack logic. Can you provide any references for additional context?
* https://github.com/k8ssandra/cass-operator/issues/397 removed the dependency on k8s.io/kubernetes. You mentioned that it was recommended by Kubernetes devs. Can you provide any references for additional context?

I believe operator-sdk v1.23.0 moves to Kustomize v4.5.5. Let's go ahead and move to v4.5.7 to be consistent with cass-operator.

**Environment**

* K8ssandra Operator version:

    `v1.2.0`

**Comment by burmanm** [comment]
Ah, the perf improvements were in 4.5.5, regardless - 4.5.6 / 4.5.7 has these improvement which we use a hacks for currently (name + namespace ambiquities, namespace transformer improvements for roles):

https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.5.6

(4.5.7 is a re-release of 4.5.6 which had a dependency bug)

**Comment by burmanm** [comment]
For the k8s.io/kubernetes, here are the repository rules: https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md

(Note the Core Repositories part). The github.com/kubernetes/kubernetes is a building part, and modules are placed under staging directory there. 

It's funny that I can't find anywhere it documented, but here's from Kubernetes issue which is the sort of comment that's usually referred:

https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364

**Comment by jsanda** [comment]
I want to point out that https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364 actually states that depending on `k8s.io/kubernetes` is not supported.

**Comment by olim7t** [comment]
`k8s.io/kubernetes` is only used for a the `hash.DeepHashObject` used [here](https://github.com/k8ssandra/k8ssandra-operator/blob/main/pkg/medusa/requests.go#L249) and [here](https://github.com/k8ssandra/k8ssandra-operator/blob/main/pkg/utils/hash.go#L11).

The implementation is pretty straightforward, and I think the licenses will allow us to copy it to our codebase.
