### ISSUE TITLE
K8SSAND-1820 ⁃ Removing Stargate triggers a DC restart

### ISSUE THREAD

**Issue by adutra** [k8ssandra/k8ssandra-operator#714]
**What happened?**

When Stargate is removed from a K8ssandraCluster object suing Cassandra 4.0, this triggers a DC restart.

**Did you expect to see something different?**

I expect no DC restart.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a cluster with 1 DC and Stargate
1. Delete Stargate from the CRD
1. Observe the DC being restarted

**Environment**

* K8ssandra Operator version:

1.2

**Anything else we need to know?**:

Due to this code in the k8ssandra controller:

```
if dcConfig.ServerVersion.Major() != 3 && kc.HasStargates() {
	// if we're not running Cassandra 3.11 and have Stargate pods, we need to allow alter RF during range movements
	cassandra.AllowAlterRfDuringRangeMovement(dcConfig)
}
```

I suggest that we always call `cassandra.AllowAlterRfDuringRangeMovement(dcConfig)` for Cassandra 4.0, regardless of whether we have Stargate nodes.

See also https://github.com/stargate/stargate/issues/1274.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1820) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1820
┆priority: Medium

**Comment by adejanovski** [comment]
> I suggest that we always call cassandra.AllowAlterRfDuringRangeMovement(dcConfig) for Cassandra 4.0, regardless of whether we have Stargate nodes.

I agree 👍
