### ISSUE TITLE
K8SSAND-1856 ⁃ Expose additional fields from the cassdc spec in k8ssandra-operator

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#740]
We're not currently exposing the following fields from the CassandraDatacenter spec:

* .spec.managementApiAuth
* .spec.podTemplateSpec.SecurityContext

It would be nice to expose them for some advanced use cases.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1856) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1856
┆priority: Medium

**Comment by jsanda** [comment]
Can you elaborate on the use cases?
