### ISSUE TITLE
K8SSAND-1884 ⁃ Scale down / scale up created an infinite cleanup task loop

### ISSUE THREAD

**Issue by sinohC** [k8ssandra/k8ssandra-operator#760]
Hi everyone!
I have performed the migration of an old datastax/cass-operator cluster to k8ssandra-operator v1.2.0 following this guide :

https://k8ssandra.io/blog/tutorials/how-to/how-to-migrate-an-existing-cluster-to-k8ssandra-operator-without-any-downtime/

Everything worked perfectly fine, and now I don't have my old cluster anymore. Problem came when I tested to scale down - scale up the new cluster.

The cleanup task that is executed during the scale up is being recreated on a loop, and actually being executed 35k times. Because of that, the CassandraDatacenter cannot be modified , showing this error: 

**_CassandraDatacenter generation is 11, but latest observed generation is 10_** 

Looks like this issue was already fixed https://github.com/k8ssandra/cass-operator/issues/186, but maybe is not ?

Also, any idea how could I finish the loop?

Regards!

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1884) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-1884
┆Priority: Medium
┆Link To Issue: https://k8ssandra.atlassian.net/browse/K8SSAND-1884

**Comment by burmanm** [comment]
Most likely your CRD is out-of-date and that causes it. CassandraDatacenter CRD should have: Status.TrackedTasks as a field.

**Comment by jsanda** [comment]
@sinohC Did you have out of date CRDs?

**Comment by sinohC** [comment]
Hi @jsanda ,
Yes, looks like the old CRD was not working fine... That fixed the issue.
THanks all!

**Comment by adejanovski** [comment]
Thanks for the update, I'll go ahead and close this issue.
