### ISSUE TITLE
v0.38.4:  Error: services "k8ssandra-operator-webhook-service" already exists when deploying with helm

### ISSUE THREAD

**Issue by caniko** [k8ssandra/k8ssandra-operator#769]
I am having a problem with the webhook service. It gets deployed by helm, but there is a collision with a webhook downstream from the chart. I can confirm that rolling back to `0.38.2` solves the issue.

I am using the following terraform:
```
resource "helm_release" "k8ssandra-operator" {
  name = "k8ssandra-operator"
  namespace = "syndb-k8ssandra"

  repository = "https://helm.k8ssandra.io/stable"
  chart = "k8ssandra-operator"

  set {
    name = "global.clusterScoped"
    value = true
  }
}
```
You can also reproduce through `helm` (provided `0.38.4` is latest):
```
helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --create-namespace 
```
The error raised by terraform:
```
module.k8ssandra.helm_release.k8ssandra-operator: Creating...
╷
│ Warning: Helm release "k8ssandra-operator" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform again.
│ 
│   with module.k8ssandra.helm_release.k8ssandra-operator,
│   on modules/k8ssandra/resource.tf line 5, in resource "helm_release" "k8ssandra-operator":
│    5: resource "helm_release" "k8ssandra-operator" {
│ 
╵
╷
│ Error: services "k8ssandra-operator-webhook-service" already exists
│ 
│   with module.k8ssandra.helm_release.k8ssandra-operator,
│   on modules/k8ssandra/resource.tf line 5, in resource "helm_release" "k8ssandra-operator":
│    5: resource "helm_release" "k8ssandra-operator" {
```
`helm -n syndb-k8ssandra list`:
```
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS  CHART                           APP VERSION
k8ssandra-operator      syndb-k8ssandra 1               2022-11-16 09:21:10.457506861 +0100 CET failed  k8ssandra-operator-0.38.4       1.3.0
```

**Comment by burmanm** [comment]
The limitation here is "k8ssandra-operator" can't be used as the release-name since it's the same as chart-name and that causes a conflict in the resource generation. It modifies the cass-operator's webhook-service to have the same name as k8ssandra-operator's webhook-service.

**Comment by burmanm** [comment]
And this is because k8ssandra-operator chart uses ``{chart.Name}-webhook-service`` as the resource name, while cass-operator uses ``{release.Name}-webhook-service``

**Comment by Cavein254** [comment]
Experiencing the same problem using `helm v4.5.7` following the [documentation] (https://github.com/k8ssandra/k8ssandra-operator/blob/main/docs/install/README.md?utm_source=datastaxmedium&utm_medium=blog&utm_campaign=K8ssandra-amplification&utm_term=cloud-native-devplay&utm_content=multi-cluster-deployments-K8ssandra-Operator-M91)

`Error from server (NotFound): serviceaccounts "k8ssandra-operator" not found`

**Comment by adejanovski** [comment]
Hi @Cavein254, your problem seems to be different, doesn't it?

@burmanm, do you think we could prevent the webhook names from conflicting? We could maybe compare the release and chart names and act accordingly if they clash?

**Comment by bderrly** [comment]
The installation documentation [example](https://docs-v2.k8ssandra.io/install/local/single-cluster-helm/#deploy-k8ssandra-operator) causes this error to trigger.

**Comment by hanhduynguyen** [comment]
I'm stuck here as well. 

 helm install k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --create-namespace

Error: INSTALLATION FAILED: services "k8ssandra-operator-webhook-service" already exists

**Comment by thefloppyfaker** [comment]
+1

**Comment by caniko** [comment]
Hello everyone, this is certainly annoying indeed; moreover, if you read the reply feom the devs, the fix is very straight forward: Don't use `k8ssandra-operator` as name:
```shell
helm install k8ssandra-operator
--set name=my-k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --create-namespace
```
I haven't tested this, I use terraform and currently am AFK (typing from my phone).

**Comment by burmanm** [comment]
No need to do --set-name, just use: ``helm install k8ssandra k8ssandra/k8ssandra-operator -n ..``, the second parameter is the used name.

**Comment by hanhduynguyen** [comment]
try multiple way but still faced the same issue. 

 helm install hh-k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --set global.clusterScoped=true --create-namespace
Error: INSTALLATION FAILED: services "hh-k8ssandra-operator-webhook-service" already exists

**Comment by hanhduynguyen** [comment]
helm install my-k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator --create-namespace
Error: INSTALLATION FAILED: services "my-k8ssandra-operator-webhook-service" already exists

**Comment by 1swaraj** [comment]
Same issue

**Comment by adejanovski** [comment]
Hi folks,

sorry for this problem, we're investigating it.
In the meantime, the workaround seems to be avoiding using a release name that contains `k8ssandra-operator`.

Won't work:

- `my-k8ssandra-operator`
- `k8ssandra-operator2`

Will work:
- `k8ssandra`
- `k8ssandra-cluster`

**Comment by 1swaraj** [comment]
With this we get the issue :- serviceaccounts "k8ssandra-operator" not found

**Comment by hanhduynguyen** [comment]
Thanks Adejanoski. 

It works with k8ssandra-cluster.

**Comment by adejanovski** [comment]
> With this we get the issue :- serviceaccounts "k8ssandra-operator" not found

The name of the generated service account depends on the Helm release name.
Check which service account was generated for you by listing the service accounts. It should be `<release-name>-k8ssandra-operator`.

**Comment by hanhduynguyen** [comment]
I saw it created too many container include those failed to create before.
How do I clean up the previous failed container ?

**Comment by hanhduynguyen** [comment]
I managed to clean up the pod with delete option. 
helm delete my-k8ssandra-operator k8ssandra/k8ssandra-operator -n k8ssandra-operator

**Comment by burmanm** [comment]
This should work now, in version 0.39.0
