### ISSUE TITLE
Update to go 1.19

### ISSUE THREAD

**Issue by burmanm** [k8ssandra/k8ssandra-operator#770]
**What is missing?**
Almost everyone in our team develops with go1.19 already, so forcing go.mod to have something older while actually compiling with it just feels silly. Also, go 1.19 is already few months old so it shouldn't pose any serious stability issues anymore.

At the same time, update operator-sdk to 1.25.1 (to keep up with the go 1.19) and to keep up with that, update to Kubernetes 1.25.

**Why do we need it?**

**Environment**

* K8ssandra Operator version:

    `Insert image tag or Git SHA here`
    
    

**Anything else we need to know?**:

**Comment by olim7t** [comment]
I'm taking this because I need to upgrade cass-operator for #776, and the new version uses 1.19.
