### ISSUE TITLE
Expose perNodeConfigInitContainer.Image through CRD

### ISSUE THREAD

**Issue by dnugmanov** [k8ssandra/k8ssandra-operator#781]
**What is missing?**
Now image for per-node configuration hardcoded in https://github.com/k8ssandra/k8ssandra-operator/blob/d58b87de760da5eb10c8579898d0da303f3a7914/pkg/nodeconfig/mount.go#L29

Why dont we expose image config  like JmxInitContainerImage with default kubebuilder annotation?
https://github.com/k8ssandra/k8ssandra-operator/blob/06a89fc154384bb77661c1e655e376c0353ab72b/apis/k8ssandra/v1alpha1/k8ssandracluster_types.go#L343

It will be user get the ability to override own registry,repo,tag

**Why do we need it?**
Many installation restricts public access, for example, we have admission controller that cheks all images are pulled only from private registry

**Environment**

* K8ssandra Operator version: 1.4.0

**Comment by jsanda** [comment]
All images should be configurable so yes I agree that this should be addressed.

@adejanovski Let's get this prioritized in the backlog.

**Comment by adejanovski** [comment]
sounds good 👍

**Comment by studypyth** [comment]
@jsanda @adejanovski hi, can i implement this feature request myself? as i see issue is not "in progress" state https://github.com/orgs/k8ssandra/projects/8

**Comment by jsanda** [comment]
@studypyth Go4it 😄 Feel free to reach out here or on Discord with any questions you have along the way.
