### ISSUE TITLE
K8ssandra-operator is incompatible with Kubernetes >= 1.24

### ISSUE THREAD

**Issue by 1swaraj** [k8ssandra/k8ssandra-operator#793]
**What happened?**
K8ssandra-operator is incompatible with K8s >= 1.24.0
Post running the create-config.sh script the k8ssandra-operator starts restarting throws these errors :- 
ERROR   setup   unable to create manager cluster connections    {"error": "Get \"https://172.18.0.2:6443/api?timeout=32s\": x509: certificate signed by unknown authority"}

**Did you expect to see something different?**
Expected the k8ssandra-operator to be unchanged

**Findings**
Recently the new version of K8s was released and this version stops the creation of secrets associated with service accounts. 
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes

**How to reproduce it (as minimally and precisely as possible)**:
Deploy k8ssandra-operator to kubernetes 1.24.0 or greater

**Environment**

* K8ssandra Operator version: 1.4.0

    `Insert image tag or Git SHA here`
    
    

* Kubernetes version information:

    `kubectl version`
    

* Kubernetes cluster kind:

    insert how you created your cluster: kops, bootkube, etc.

* Manifests:

```
insert manifests relevant to the issue
```

* K8ssandra Operator Logs:

```
insert K8ssandra Operator logs relevant to the issue here
```

**Anything else we need to know?**:

**Comment by adejanovski** [comment]
Hi @1swaraj,

k8ssandra-operator works with k8s v1.25, but we seem to have a problem with helm installations with multi cluster setups.
We'll investigate this issue and provide a fix ASAP.
