### ISSUE TITLE
Add a Cassandra struct in the Telemetry spec for the new metrics endpoint

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/k8ssandra-operator#815]
A new TelemetrySpec.Cassandra struct must be added to configure the new metrics endpoint.
The values there will be used to generate a config map using [this file format](https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/471b7bc87b5b3ece9e5fe798b6cbcd48a281ad8e/management-api-agent-common/src/test/resources/collector.yaml).
Filters can reuse Prometheus's [RelabelConfig](https://github.com/prometheus-operator/prometheus-operator/blob/e4e27052f57040f073c6c1e4aedaecaaec77d170/pkg/apis/monitoring/v1/types.go#L1150) struct, reduced to just the supported fields for our filters.

**Comment by Miles-Garnsey** [comment]
@adejanovski where does this ConfigMap need to be mounted?

**Comment by adejanovski** [comment]
> @adejanovski where does this ConfigMap need to be mounted?

You can check [this file](https://github.com/k8ssandra/management-api-for-apache-cassandra/blob/f631db71b4f4bfefb3791e42b080e6c2df3f7fc5/management-api-agent-common/src/main/java/io/k8ssandra/metrics/config/ConfigReader.java) for more information.
In a nutshell, by default the mgmt api will look for the config file under `$MAAC_PATH/configs/metric-collector.yaml`.
This path can be overridden with the `collector-config-path` system property.
