### ISSUE TITLE
docker.io/k8ssandra/k8ssandra-operator:1.5.1: not found

### ISSUE THREAD

**Issue by WoodyWoodsta** [k8ssandra/k8ssandra-operator#897]
**What happened?**
I tried to install the `1.5.1` helm chart, but it deployed `k8ssandra-operator` with the image `docker.io/k8ssandra/k8ssandra-operator:1.5.1`, which is missing the `v` prefix in the tag. As a result, the pull failed (and has consequently left my cluster in an un-working state, but that's for me to deal with 😄 ).

**Did you expect to see something different?**
`k8assandra-operator` deploys successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Install the `1.5.1` helm chart.

**Environment**

* K8ssandra Operator version:

    `1.5.1`
    
    

* Kubernetes version information:

    `v1.26.1`
    

* Kubernetes cluster kind:

    `kubeadm`

**Comment by adejanovski** [comment]
Thanks for reporting this issue.
Our new Helm release process did have a problem indeed and didn't include the `v` in the image tag.
We released v1.5.2 with a proper version tag.

if you still want to use v1.5.1 instead, you can work around the issue by adding `--set image.tag=v1.5.1` when invoking `helm install/upgrade`.

**Comment by WoodyWoodsta** [comment]
Have upgraded to v1.5.2, thanks!
