### ISSUE TITLE
Using Cassandra 4.1 config values prevents startup

### ISSUE THREAD

**Issue by WoodyWoodsta** [k8ssandra/k8ssandra-operator#898]
**What happened?**
I've upgraded to k8ssandra `1.5.0`, and consequently updated the `serverVersion` to `4.1.0`. I took this as an opportunity to use the new config parameters for cassandra, such as `materialized_views_enabled`. However, the dc fails to start completely with the error:

```
org.apache.cassandra.exceptions.ConfigurationException: Config contains both old and new keys for the same configuration parameters, migrate old -> new: [...]
```

This is likely because `cassandra` is not invoked with `-Dcassandra.allow_new_old_config_keys=true`, but I appreciate that this may not be the right solution because the property merging may not result in the config that's provided as part of the `K8ssandraCluster` being the final values.

**Did you expect to see something different?**
I expected to be able to use `4.1.0` config properties.

**How to reproduce it (as minimally and precisely as possible)**:
Start up a `K8ssandraCluster` with:

```yaml
spec:
  cassandra:
    datacenters:
      - config:
        cassandraYaml:
          materialized_views_enabled: true
```

**Environment**

* K8ssandra Operator version:

    `1.5.0`
    
    

* Kubernetes version information:

    `v1.26.1`
    

* Kubernetes cluster kind:

    kubeadm

**Anything else we need to know?**:

I've tried to remove and re-add the `K8ssandraCluster`, with the same result.

**Comment by burmanm** [comment]
Closing this, 1.10.3 supports newer configuration.
