### ISSUE TITLE
Revisit Vector telemetry's default config

### ISSUE THREAD

**Issue by olim7t** [k8ssandra/k8ssandra-operator#914]
Following #906, enabling Vector telemetry does not inject a new sidecar anymore, it just modifies the existing system-logger sidecar (which is now based on Vector, see k8ssandra/cass-operator#498).

If the user also provides custom config via `cassandra.telemetry.vector.components`, it will get merged with a "default" Vector config hard-coded into k8ssandra-operator.

Where it gets confusing is that that "default" config is not the same as what you get from cass-operator if telemetry is disabled. This is apparent if you create a cluster like so:
```yaml
spec:
  cassandra:
    telemetry:
      vector:
        enabled: true
    datacenters:
      ...
```
The Kubernetes logs of the system-logger container are now stripped of all contextual information:
```
Seed provider couldn't lookup host demo-dc1-additional-seed-service
Creating replication strategy none params KeyspaceParams{durable_writes=true, replication=ReplicationParams{class=org.apache.cassandra.locator.NetworkTopologyStrategy, dc1=1}}
Configured datacenter replicas are dc1:rf(1)
```
This is because k8ssandra-operator's "default" config include a transformation that parses the Cassandra log line (`pkg/telemetry/vector.go`):
```
. |= parse_groks!(.message, patterns: [
  "%{LOGLEVEL:loglevel}\\s+\\[(?<thread>((.+)))\\]\\s+%{TIMESTAMP_ISO8601:timestamp}\\s+%{JAVACLASS:class}:%{NUMBER:line}\\s+-\\s+(?<message>(.+\\n?)+)",
  ]
)
```
This extracts a `message` fields that overrides the initial message (what used to be the log line). And then we send that transformation to the console:
```go
	systemLogSink := telemetry.VectorSinkSpec{
		Name:   "console_log",
		Type:   "console",
		Inputs: []string{"parse_cassandra_log"},
		Config: `target = "stdout"
encoding.codec = "text"
`,
	}
```

I suggest we get rid of that parsing phase, it serves no purpose here (and loses context). The defaults to be merged with the user config should be mostly similar to [cass-operator's defaults](https://github.com/k8ssandra/cass-operator/blob/master/config/logger/vector_config.toml).

If we need log parsing in downstream projects, we can simply reimplement the `parse_cassandra_log` phase there, instead of inheriting it (it will also be easier to understand).

**Comment by burmanm** [comment]
Alternatively, we just reconstruct the output in the console sink (a single remap). The idea why I wanted this to be in the k8ssandra-operator is to provide simple parsed log output no matter which system the user is using. The user only needs to add a new sink that listens to this output.
