### ISSUE TITLE
Migration to k8ssandra-operator using allocate_tokens_for_keyspace

### ISSUE THREAD

**Issue by sinohC** [k8ssandra/k8ssandra-operator#945]
Hi!

We are planning to migrate an old cass-operator cluster using version 3.11.6 and single token ranges on its nodes to a k8ssandra-operator(v.1.5) cluster using version 3.11.13 , with 8 vnodes.

For the new k8ssandra-operator DC we will need to set **allocate_tokens_for_keyspace** property as **allocate_tokens_for_local_replication_factor** is only usable starting from Cassandra 4.

Is **allocate_tokens_for_keyspace** property still available for K8ssandra-operator v.1.5? I don't find any reference about it...

**Comment by sinohC** [comment]
Ok, you are probably right :) . Coming back to your procedure:

**_"you'll probably need to initialize the new k8ssandra DC with 3 nodes, then change the replication settings for your user keyspaces, modify the config to add auto_bootstrap: false and allocate_tokens_for_keyspace: <your keyspace>, and then expand this DC to the desired size, and finally perform a rebuild using a CassandraTask."_**

So you mean to:
- Add 3 nodes with no data but bootstrapping them (RF will be disabled on DC2 at this point) 
-  Then change the RF pointing also to DC2 (nodes will start to receive writes at this point and reads are LOCAL_QUORUM on DC1) 
- Modify the config to add `auto_bootstrap: false` and `allocate_tokens_for_keyspace`
- Expand the cluster and rebuild all 6 nodes

If this is the case... will the first 3 nodes enjoy the benefits from the token allocation?

**Comment by adejanovski** [comment]
> If this is the case... will the first 3 nodes enjoy the benefits from the token allocation?

They wont, but that's how the 3.11 algorithm works. Things are definitely better in 4.0.
You can only hope that the 3 additional nodes will properly balance the DC.
Or, you can use per node config to forcefully set the initial tokens of the first three nodes, using the [PerNodeConfigMapRef](https://docs.k8ssandra.io/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-1.5/#k8ssandraclusterspeccassandradatacentersindexpernodeconfigmapref) field to pass it a config map that contains the initial tokens for these three nodes. 
Here's [a sample](https://github.com/adutra/k8ssandra-operator/blob/560aed5a8c52c047ffd1e876007ef6a332b95e2f/test/testdata/fixtures/single-dc-per-node-config/k8ssandra.yaml#L1-L11) per node config map that sets the initial tokens.

**Comment by adejanovski** [comment]
Sure thing, happy to get an update once you're done with it.
