### ISSUE TITLE
MedusaBackupJob fetches backup pods from all namespaces if installed in cluster-scope

### ISSUE THREAD

**Issue by shaotingcheng** [k8ssandra/k8ssandra-operator#946]
**What is missing?**
Curretnly, MedusaBackupSchedule will look for the cassandraDatacenter name only to launch the backup.
Maybe it's better to add more filter, like namespace.

**Why do we need it?**
In my environment, I create a k8ssandracluster per namespace. Each k8ssandracluster has the same cassandraDatacenter name.
It's impossible to set the backup separately for each k8ssandracluster in the different namespace.

**Environment**

kubelet V1.21.14-00

* K8ssandra Operator version: V1.5.2

**Anything else we need to know?**:
May I missed something. Any other filter for MedusaBackupSchedule ?

**Comment by burmanm** [comment]
Hey,

Both MedusaBackupSchedule as well as MedusaBackupJob use the same definition for backup jobs. There shouldn't be any confusion between objects, as each CassandraDatacenter name can only appear once in the same namespace (and the BackupJob / Schedule has namespace tied to it).

That is - this is tied to the CassandraDatacenter name, not K8ssandraCluster's DatacenterName (those can overlap, but are not used for backups). So create the MedusaBackupSchedule / BackupJob to the same namespace as the datacenter and it will only backup that datacenter.

@adejanovski This is indeed a confusing issue if one uses DatacenterName overrides, the backups are going to require user to know about the CassandraDatacenter ObjectMeta.Name, not anything with DatacenterName.

**Comment by adejanovski** [comment]
> @adejanovski This is indeed a confusing issue if one uses DatacenterName overrides, the backups are going to require user to know about the CassandraDatacenter ObjectMeta.Name, not anything with DatacenterName.

yes, we knew that the name override could create some confusion one way or the other. Maybe we can drop a sentence in the docs to make it clear the `CassandraDatacenter` value should be the k8s object name of the DC?
But it is not what's reported here though and you're right about having to place the MedusaBackupSchedule/MedusaBackup objects in the right namespace.

**Comment by adejanovski** [comment]
I'll go ahead and close this ticket as what you're asking is already possible @shaotingcheng.
Feel free to reopen if you run into more issues there.

**Comment by shaotingcheng** [comment]
@adejanovski @burmanm Thanks for the prompt replies. 

Even though I replace the MedusaBackupSchedule in a particular namespace, the backup will include all nodes among different namespaces.

Here is my environment:
I installed k8ssandra-operator in "k8ssandra-operator" namespace with value `clusterScoped: true`
I have 7 other namespaces, ns1, ns2, ..., ns7 to run 7 independent Cassandra clusters.
In each namespace, I configured them with the same way.
* 1 CassandraDatacenter whose name is "**dc1**"
* 5 Cassandra POD
** cassandra-dc1-r1-sts-0
** cassandra-dc1-r1-sts-1
** cassandra-dc1-r2-sts-0
** cassandra-dc1-r2-sts-1
** cassandra-dc1-r3-sts-0

If I place a MedusaBackupSchedule in ns1 namespace
```
apiVersion: medusa.k8ssandra.io/v1alpha1
kind: MedusaBackupSchedule
metadata:
  name: medusa-backup-schedule
  namespace: ns1
spec:
  backupSpec:
    backupType: differential
    cassandraDatacenter: dc1
  cronSchedule: 33 6 * * *
  disabled: false
```

Here is the status of MedusaBackupJob
```
status:
  failed:
    - cassandra-dc1-r1-sts-0
    - cassandra-dc1-r2-sts-0
    - cassandra-dc1-r3-sts-0
    - cassandra-dc1-r1-sts-1
    - cassandra-dc1-r2-sts-1
    - cassandra-dc1-r1-sts-1
    - cassandra-dc1-r2-sts-0
    - cassandra-dc1-r3-sts-0
    - cassandra-dc1-r2-sts-1
    - cassandra-dc1-r3-sts-0
    - cassandra-dc1-r2-sts-1
    - cassandra-dc1-r2-sts-0
    - cassandra-dc1-r1-sts-1
    - cassandra-dc1-r1-sts-1
    - cassandra-dc1-r2-sts-0
    - cassandra-dc1-r2-sts-1
    - cassandra-dc1-r2-sts-0
    - cassandra-dc1-r1-sts-0
    - cassandra-dc1-r3-sts-0
    - cassandra-dc1-r3-sts-0
    - cassandra-dc1-r1-sts-0
    - cassandra-dc1-r1-sts-1
    - cassandra-dc1-r2-sts-1
    - cassandra-dc1-r2-sts-0
    - cassandra-dc1-r1-sts-0
    - cassandra-dc1-r1-sts-1
    - cassandra-dc1-r3-sts-0
    - cassandra-dc1-r2-sts-0
    - cassandra-dc1-r2-sts-1
  finishTime: '2023-03-15T06:09:45Z'
  finished:
    - cassandra-dc1-r2-sts-1
    - cassandra-dc1-r1-sts-1
    - cassandra-dc1-r3-sts-0
    - cassandra-dc1-r1-sts-0
    - cassandra-dc1-r1-sts-0
    - cassandra-dc1-r1-sts-0
  startTime: '2023-03-15T06:00:15Z'
spec:
  backupType: differential
  cassandraDatacenter: dc1
```

Apparently, It includes not only POD in ns1 namespace, but all PODs among all namespace because their CassandraDatacenter  have the same name "dc1"

**Comment by burmanm** [comment]
Okay, that looks to be a bug here: https://github.com/k8ssandra/k8ssandra-operator/blob/main/pkg/medusa/utils.go#L16

It's missing NamespaceAware Client and using the ClusterScoped client instead (from quick look).
