### ISSUE TITLE
K8SSAND-843 ⁃ #95 - k8ssandra-operator should support cluster-scoped deployments

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#95]
Currently k8ssandra-operator is namespace-scoped. It only watches objects in specified namespaces which defaults to the namespace in which the operator is deployed. Interestingly the operator can be configured to watch different namespaces in remote clusters as compared to the ones it watches in the control plane cluster.

We should be able to configure the operator to be cluster-scoped such that it will watch object across all namespaces. Furthermore we should be able to create a multi-DC C* cluster (within a single k8s cluster) where each DC is in a different namespace.

There are a number of things that need (or may need) to be done for this including:

* Implement changes in operator code
  *  Some initial work has been started in #116. I did an initial review and pointed out some other changes that are needed.
  * K8ssandraClusterReconciler configures a watch on Stargate and CassandraDatacenter objects with a mapping function that checks for the cluster.  We may need to update the value of the label to also include the namespace of the K8ssandra cluster (or alternatively add a label for the namespace of the K8ssandraCluster).
*   Update kustomize manifests 
*  Update Helm chart
* Add `envtest` integration tests for
  * Multi-DC cluster in a single cluster across multiple namespaces
  * Multi-DC cluster in multiple cluster across multiple namespaces
* Add e2e tests for
  * Multi-DC cluster in a single cluster across multiple namespaces
  * Multi-DC cluster in multiple cluster across multiple namespaces 
* Update install guide 

It might make sense to break some of this up into multiple tickets.

Lastly note that the work describe here should also take care of #19.

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-843) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆Issue Number: K8SSAND-843
┆Priority: Medium

**Comment by burmanm** [comment]
This is the method used by cass-operator to do it (should work with k8ssandra-operator also with small modifications):

https://github.com/k8ssandra/cass-operator/blob/master/config/cluster/kustomization.yaml

**Comment by jsanda** [comment]
Thanks for the reference. I think we want this knock this out in support of #19.

**Comment by jsanda** [comment]
@burmanm I'd like to knock this out this week. I pushed some more commits to my [branch](https://github.com/jsanda/k8ssandra-operator/tree/cluster_deploy). I am happy to take the ticket, or I can sync with your branch. Let me know if you have a preference.

**Comment by burmanm** [comment]
Go ahead, I don't have time this week to proceed with this.
