### ISSUE TITLE
Create replicated superuser secret before creating CassandraDatacenters

### ISSUE THREAD

**Issue by jsanda** [k8ssandra/k8ssandra-operator#97]
We need k8ssandra-operator to create and manage the default superuser secret so that each CassandraDatacenter does not wind up with a different set of credentials.

Now that #53 has been merged the K8ssandraCluster controller can do the following:

* Create a secret with default superuser and random password
  * Or allow the user to specify a secret with credentials
* Create a ReplicatedSecret that references the the superuser secret

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-846) by [Unito](https://www.unito.io)
┆Reviewer: 5e66ca0cae59460cfb01a13c
┆Fix Versions: k8ssandra-2.0.0-alpha
┆Issue Number: K8SSAND-846
┆Priority: Medium

**Comment by burmanm** [comment]
We should probably add a single ReplicatedSecret with something like matching all labels "k8ssandra.io/replicate=true" or something. And we'll add that label to all the secrets we create.
