### ISSUE TITLE
CI/CD does not produce images for some commits

### ISSUE THREAD

**Issue by Miles-Garnsey** [k8ssandra/k8ssandra-operator#985]
**What happened?**

CI/CD runs for documentation commits don't produce images. This leads to errors when you try to reference the k8ssandra-operator kustomizations from downstream kustomizations.

All commits on `main` must create an image to avoid kustomizations being broken.

**Definition of done**

All commits (inc. docs commits/whatever) generate an image and kustomizations that can be deployed.

**Comment by adejanovski** [comment]
Sounds good to me if that avoids confusion.
Maybe we could have docs update build and push an image directly instead of going through the whole CI process?
That can help unclutter our CI queue.
